### ISSUE TITLE
How to search a list of distinct numbers for hidden layer sizes more efficiently?

### ISSUE THREAD

**Issue by yuntaowu2000** [microsoft/FLAML#1027]
I would like to search for a list of hidden layer sizes using the code below. Both the list size and the elements are unknown.
```python
def hidden_size_sampler(config):
    layers = []
    for _ in range(np.random.randint(1, 6)):
        layers.append(np.random.randint(1, 11))
    return tuple(layers)
config = {
    "hidden": tune.sample_from(hidden_size_sampler),
}
result = flaml.tune.run(
    tune.with_parameters(train_wrapper),
    config=config,
    metric="dev_loss",
    mode="min",
    low_cost_partial_config={"num_epochs": 10},
    search_alg=flaml.tune.searcher.RandomSearch(),
    scheduler="asha",  # Use asha scheduler to perform early stopping based on intermediate results reported
    resources_per_trial={"cpu": 1, "gpu": 1},
    local_dir='logs/',
    num_samples=15,
    use_ray=True)
```
I want it to search for a list of optimal hidden sizes, e.g. [1, 2, 3, 4, 5] or [7, 5, 3] rather than a list of fixed numbers like [3,3,3] or [5,5,5,5].
The default `flow2` search algorithm will throw exception for this kind of sampling, so I have to use `RandomSearch`, but the result may not be optimal. Is there a better search algorithm for this kind of list search?

**Comment by ZmeiGorynych** [comment]
Or what approach did you go with?

**Comment by ZmeiGorynych** [comment]
> Presumably you have a maximal number of layers you're willing to search up to? One way I could think of is a nested search space, where at the top level you select the number of layers, and then conditional on that you define the search space for layer sizes separately for each number of layers value. You could generate that config programmatically so it's not too tedious to write by hand.

You could even do a recursive search space (finite depth), at each step you decide whether you want to add one more layer, and if true select its size and see if you want to add one more layer, etc
