### ISSUE TITLE
It is not possible to persist flamlized estimators

### ISSUE THREAD

**Issue by tyler-romero** [microsoft/FLAML#1061]
Sklearn-style models are [persisted via pickle](https://scikit-learn.org/stable/model_persistence.html), but flamelized estimators cannot be persisted in this way because they define the flamelized model class as a local inside of the `flamlize_estimator` function [here](https://github.com/microsoft/FLAML/blob/main/flaml/default/estimator.py#LL29C6-L29C6).

Repro:
```python
from flaml.default import XGBClassifier as FlamlXGBClassifier
import pickle as pkl
flaml_classifier = FlamlXGBClassifier()
pkl.dumps(FlamlXGBClassifier)
```
`AttributeError: Can't pickle local object 'flamlize_estimator.<locals>.EstimatorClass'`

Desired behavior:
dumping and loading models via pickle "just works".

**Comment by sonichi** [comment]
Thanks for the suggestion. I don't know how to solve this issue except hardcoding the class definition statically instead of dynamically. Help is appreciated.

**Comment by EgorKraevTransferwise** [comment]
Why not use `cloudpickle` or `dill` instead of `pickle`. `pickle` has so many limitations...

**Comment by tyler-romero** [comment]
cloudpickle is good enough, thanks!
