### ISSUE TITLE
import package error

### ISSUE THREAD

**Issue by windwine** [microsoft/FLAML#11]
Hi,

I used pip install and 
from flaml import AutoML
gave me the error of

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\windwine8700\\anaconda3\\lib\\site-packages\\settings.json'

I am using python 3.83. Is there a way to solve this issue? Thanks.

Best,

Jiaqi

**Comment by sonichi** [comment]
Thanks Jiaqi. settings.json is missing in the Pypi package though it's in the repo. We'll fix it and publish a new version to Pypi soon. A temporary fix is to copy the settings.json in the root of this repo to C:\Users\windwine8700\anaconda3\lib\site-packages.

Best,
Chi

**Comment by windwine** [comment]
It is fixed now.谢谢。

**Comment by ankitadhawan05** [comment]
I got this error message while installing flaml

ERROR: Command errored out with exit status 1:
