### ISSUE TITLE
More details on low_cost_partial_config?

### ISSUE THREAD

**Issue by stepthom** [microsoft/FLAML#110]
`fit()` is stopping early with the following message:

```
[flaml.automl: 06-17 12:55:08] {1013} INFO - iteration 41, current learner lrl1
No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'.
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
```

I cannot find any details in the documentation as to what exactly `low_cost_partial_config` is, or what I should be setting it to. Any pointers or guidance would be appreciated.

**Comment by stepthom** [comment]
Oops, nevermind. I was not using FLAML's `fit()` properly. My mistake. Fixed now.

**Comment by qingyun-wu** [comment]
Hi @jezerro,

Please find a brief explanation about it on this wiki page: [About low_cost_partial_config ](https://github.com/microsoft/FLAML/wiki/About-%60low_cost_partial_config%60). Please let us know if it is still not clear to you. Thank you!
