### ISSUE TITLE
Parallel tuning with Spark is no longer possible if joblib isn't pinned to < 1.3.0

### ISSUE THREAD

**Issue by badjouras** [microsoft/FLAML#1102]
When `use_spark` is set to True, tune.py tries imports `register_spark` from `joblibspark` and [calls it](https://github.com/microsoft/FLAML/blob/e3ca95bf8a5cc9c86638dab8ef0eb44bc1f3ee6f/flaml/tune/tune.py#L627).

However, since joblib 1.3.0 was released yesterday, a class used by `register_spark` no longer exists, which causes any attempted use of parallel tuning with Spark to fail:

![image](https://github.com/microsoft/FLAML/assets/47984759/b32ab9f9-f97a-4aad-a698-bcfd48349a7c)

I've already created [an issue](https://github.com/joblib/joblib-spark/issues/49) in the joblib-spark GitHub repo, but I thought I should let you guys know.

**Comment by thinkall** [comment]
Thank you @badjouras , I've addressed the issue in PR #1100, and the actual solution is https://github.com/joblib/joblib-spark/pull/48
