### ISSUE TITLE
Agent paper writing

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/FLAML#1116]
Please feel free to suggest/add tasks or volunteer to help with tasks!

```[tasklist]
### Tasks
- [ ] Introduce the design, implementation, and usage features of interactive agents in flaml/autogen based on the current documentation, code examples
- [ ] Evaluation on relevant benchmarks.
```

**Comment by sonichi** [comment]
The paper is about decision making, especially multi-step tasks.

**Comment by Satarupa22-SD** [comment]
@qingyun-wu I would like to work on this. Can you please assign me this task. Thanks!

**Comment by sonichi** [comment]
The paper has been written. Thanks.
