### ISSUE TITLE
Error with custom metric when using eval_method = "cv"

### ISSUE THREAD

**Issue by stepthom** [microsoft/FLAML#112]
I'm trying to use a custom metric. I'm using the one from the test case:

https://github.com/microsoft/FLAML/blob/06045703bf90f58f3b89acb01b50c8fe2c65b93b/test/test_automl.py#L92

This works fine when `eval_method` is set to its default value of "holdout". But if I change this to "cv"`, I get an error as follows:

![image](https://user-images.githubusercontent.com/3842201/122620955-3c2ebb00-d062-11eb-94ca-b8147e0fea3b.png)

**Comment by sonichi** [comment]
Thanks @stepthom for finding the bug. This PR should fix it.
