### ISSUE TITLE
Whether UserProxyAgent's `auto_reply` should call `self.send`?

### ISSUE THREAD

**Issue by JieyuZ2** [microsoft/FLAML#1137]
It might be better that the `auto_reply` function (https://github.com/microsoft/FLAML/blob/main/flaml/autogen/agent/user_proxy_agent.py#L185) in UserProxyAgent return a string and let the `receive` method call the `send` function.

It would be easier to manage what's being sent if only `receive` can call `send` when we want to inherit UserProxyAgent  and modify `receive` or/and `auto_reply`

**Comment by sonichi** [comment]
Sounds good to me.
@qingyun-wu @kevin666aa @BeibinLi @gagb What do you think?
