### ISSUE TITLE
Question: how does FLAML handle categorical features?

### ISSUE THREAD

**Issue by stepthom** [microsoft/FLAML#117]
Hi,

I am trying to learn how FLAML handles categorical features - i.e., which encoding methods (e.g., OneHotEncoding, OrdinalEncoding) are used.

I looked through the following code: 

https://github.com/microsoft/FLAML/blob/c4c15f533fb1d9e33690a18c85eba041c80699b7/flaml/data.py#L187

but I can't see where the categorical features are actually encoded.

Also, I was wondering if different estimators will use different encodings? E.g., OrdinalEncoder for lgbm and OHE for RandomForest?

**Comment by sonichi** [comment]
Different estimators use different encodings. CatBoost uses the raw categorical features, for example. That can be found in the `_preprocess` function of each estimator in model.py.

**Comment by stepthom** [comment]
Thank you, @sonichi.

So if I understand `modey.py` correctly:

- The default/base `_preprocess` does a Ordinal-type encoding via ` X[cat_columns] = X[cat_columns].apply(lambda x: x.cat.codes)`
- LGBM's `preprocess` doesn't do anything to categorical features, effectively leaving them "raw"
- KNN's `_preprocess` drops all categorical features

**Comment by sonichi** [comment]
Yes. Both LGBM and CatBoost use raw categorical features.

**Comment by stepthom** [comment]
thank you!
