### ISSUE TITLE
Can one-way message passing be implemented in AutoGen?

### ISSUE THREAD

**Issue by Master-PLC** [microsoft/FLAML#1211]
I would like to use AutoGen to implement the style of CAMEL's task_specifier, which means sending one-way instructions through a UserProxyAgent to an AssistantAgent named task_specifier, and then having the task_specifier send out one-way messages as the initial conversation for two other auto-reply AssistantAgents.
However, it seems that I haven't found a mechanism for one-way message passing in auto_reply.

**Comment by sonichi** [comment]
You can use `send(..., request_reply=False)`
https://microsoft.github.io/FLAML/docs/reference/autogen/agentchat/responsive_agent#send

**Comment by Master-PLC** [comment]
Thank you for your suggestions~
