### ISSUE TITLE
include that `retrain_full = True` does not include the user provided validation data in the docs.

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#1228]
It'd be worth including that `retrain_full = True` does not include the user provided validation data in the docs.

_Originally posted by @RossDeVito in https://github.com/microsoft/FLAML/issues/735#issuecomment-1735978213_

**Comment by anishsoni29** [comment]
I am not able to find the supported documentation for this issue.

**Comment by sonichi** [comment]
https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#resampling-strategy

**Comment by sonichi** [comment]
Sure. Assigned.
