### ISSUE TITLE
python 3.9 support?

### ISSUE THREAD

**Issue by lostmygithubaccount** [microsoft/FLAML#125]
![image](https://user-images.githubusercontent.com/54814569/124013544-453f5680-d997-11eb-8afc-9135e04e3842.png)

it seems only up to 3.8 is supported, is 3.9? will it be? 

also 3.10 which is releasing soon?

**Comment by sonichi** [comment]
Python 3.9 works. We'll add that to the banner.

We'll try 3.10 once it's released.
