### ISSUE TITLE
Regression with Grouped kFold CV

### ISSUE THREAD

**Issue by rsangole** [microsoft/FLAML#1254]
Hello,

I have a _regression_ problem where I need to be able to use a grouped k-fold strategy (`sklearn.model_selection.GroupKFold`). However, I see in the docs that `split_type` for regression problems cannot be set to 'group' ?

Is there a way to run a regression problem with a grouped kFold approach in autoML?

Cheers!

**Comment by sonichi** [comment]
It can be, I believe.
