### ISSUE TITLE
Typo or misnaming in automl/timeseries/ts_model.py

### ISSUE THREAD

**Issue by enkiluv** [microsoft/FLAML#1279]
In version 2.x.x: (especially 2.1.1)

Lines 613 and 616:
        if (
            self.params["seasonal"] == "mul" and (train_df.y == 0).sum() > 0
        ):  # cannot have multiplicative seasonality in this case
            self.params["seasonal"] = "add"
        if self.params["trend"] == "mul" and (train_df.y == 0).sum() > 0:
            self.params["trend"] = "add"

train_df.y == 0  should be   train_df[target_col]  == 0 . Isn't it? (two places)

**Comment by Programmer-RD-AI** [comment]
Hi,
I have created a PR #1312 feel free to check it :)
Best regards
