### ISSUE TITLE
Update Optuna

### ISSUE THREAD

**Issue by bbudescu** [microsoft/FLAML#1280]
[setup.py](https://github.com/bbudescu/FLAML/blob/c48babd02fa9b3252cf49100599fb99c70794591/setup.py#L66) specifies that the required version of Optuna to be 2.8.0. However, according to `ray` docs (check out the second warning on [this](https://docs.ray.io/en/latest/tune/api/doc/ray.tune.search.optuna.OptunaSearch.html) page) :

>Please note that with Optuna 2.10.0 and earlier default `MOTPESampler`/`TPESampler` suffer from performance issues when dealing with a large number of completed trials (approx. >100). This will manifest as a delay when suggesting new configurations. This is an Optuna issue and may be fixed in a future Optuna release.

In my own experience, I have also observed the slowdown they mention.

Is there any reason for this version requirement for Optuna? And, if yes, how hard would it be update to the latest version?

**Comment by Programmer-RD-AI** [comment]
Before transitioning to newer versions, it typically involves a substantial amount of effort. I'm planning to submit a pull request to update Optuna to version 2.10.0, but the rationale behind this decision needs to be verified by Meta employees who are actively involved with detectron2.

**Comment by thinkall** [comment]
Hi @Programmer-RD-AI , as  @bbudescu  quoted,  Optuna 2.10.0 also has the performance issue. I've upgraded Optuna to support latest version in  PR #1321 .  Could you help review? Thanks.
