### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by hannahbus** [microsoft/FLAML#1298]
Many thanks for a great package. 

I've noticed a small inconsistency concerning random forests: the key in `foo.best_config()` is `max_leaves`, which differs from sklearn's `max_leaf_nodes`.

**Comment by Programmer-RD-AI** [comment]
I have created an PR #1310 to fix the issue mentioned...

**Comment by thinkall** [comment]
> I have created an PR #1310 to fix the issue mentioned...

Hi @Programmer-RD-AI , #1310 won't fix the issue, I've raised #1320 to address it.

**Comment by thinkall** [comment]
https://github.com/microsoft/FLAML/pull/1320#issuecomment-2244505018
