### ISSUE TITLE
Inconsistent Usage of .format() and f-strings in FLAML Codebase

### ISSUE THREAD

**Issue by Programmer-RD-AI** [microsoft/FLAML#1306]
In the FLAML codebase, there is inconsistent usage of string formatting methods such as .format() and f-strings (f""). This inconsistency can lead to confusion and hinder readability, especially for contributors who may expect a consistent style throughout the codebase.

Thank you for addressing this issue to improve the quality and consistency of the FLAML project.

**Comment by Borda** [comment]
I think together with bumping the min python version to 3.8 (all bellow 3.7 are not maintained already) we can normalize all to f-string
https://github.com/microsoft/FLAML/blob/0fe284b21f8eaf55cfccf5c8bb5608e50a554128/setup.py#L170
