### ISSUE TITLE
Question: Why not retrain on full dataset if eval_method = cv?

### ISSUE THREAD

**Issue by stepthom** [microsoft/FLAML#131]
I noticed that FLAML will only retrain on the full dataset if the `eval_method` parameter is set to `'holdout'`:

https://github.com/microsoft/FLAML/blob/b04b00dc9d4bc47a4135f777ca7e419854ceb140/flaml/automl.py#L910-L911

Why not retrain on full dataset for other eval_methods, such as `'cv'`?

**Comment by sonichi** [comment]
The retraining happens right after cross-validation:
https://github.com/microsoft/FLAML/blob/b04b00dc9d4bc47a4135f777ca7e419854ceb140/flaml/ml.py#L259

**Comment by stepthom** [comment]
Oh, I see - thank you very much! 👍
