### ISSUE TITLE
Flaml 2.3.0 not available on PyPi

### ISSUE THREAD

**Issue by dannycg1996** [microsoft/FLAML#1348]
### Describe the issue

The latest version of FLAML available on PyPI is 2.2.0 https://pypi.org/project/FLAML/

Could FLAML 2.3.0 also be made available there please?

This has also been mentioned in a discussion here https://github.com/microsoft/FLAML/discussions/1347, but I'm not sure how well-monitored the Discussions section is.

Thanks for any help!

### Steps to reproduce

N/A

**Comment by thinkall** [comment]
Thank you @dannycg1996 for reporting the issue. PyPi package updated.
![image](https://github.com/user-attachments/assets/fecd468c-2c74-45b3-8590-414aedcd5b31)
