### ISSUE TITLE
`_pickle_and_log_artifact` doesn't clean up pickle file after logging it as an artifact

### ISSUE THREAD

**Issue by harupy** [microsoft/FLAML#1353]
This line doesn't seem to clean up the pickle file after logging it as an mlflow artifact.

https://github.com/microsoft/FLAML/blob/c90946f3035d5886044e6f9cb30400e3a645434b/flaml/fabric/mlflow.py#L363

This broke our CI (which doesn't allow untracked files being create during test):

https://github.com/mlflow/mlflow/actions/runs/10933548130/job/30352200311

```
Untracked files found:
feature_transformer.pkl
label_transformer.pkl
```

**Comment by harupy** [comment]
I think a temporary directory/file should be used.

**Comment by thinkall** [comment]
Hi @harupy , thanks for reporting the issue. Would removing the artifact source file after logging work for you?

**Comment by harupy** [comment]
@thinkall that would work!
