### ISSUE TITLE
[Bug]: ImportError: cannot import name 'AutoML' from 'flaml'

### ISSUE THREAD

**Issue by TuringWang9527** [microsoft/FLAML#1359]
### Describe the bug

![image](https://github.com/user-attachments/assets/24717124-218a-43b8-9ea5-dbd4bc84d4c3)
can't find AutoML,I don't know why.

**Comment by tuomassiren** [comment]
pip install "flaml[automl]"
https://microsoft.github.io/FLAML/docs/Installation

**Comment by TuringWang9527** [comment]
> pip install "flaml[automl]" https://microsoft.github.io/FLAML/docs/Installation

Thank you for your reply, but I have encountered another issue
![image](https://github.com/user-attachments/assets/3c599dbf-c30e-46e9-830a-31bd9d0260ea)
![image](https://github.com/user-attachments/assets/8dc97591-946e-4a79-92fe-ac31182a7324)
TypeError: 'NoneType' object is not callable
Could you please tell me how to solve this problem？

**Comment by thinkall** [comment]
@TuringWang9527, could you try running example notebooks and see if they work? If no, it's possible that there are some issues in your conda env.

The error in your screenshot indicates that the lgbm estimator is not correctly initialized.

**Comment by albas99** [comment]
> pip install "flaml[automl]" https://microsoft.github.io/FLAML/docs/Installation

I'm having the same issue, I've tried the solution above but it's still not fixing my issue. I've checked my flaml package and it does have AutoML installed, however that doesn't seem to be solving the issue.

![image](https://github.com/user-attachments/assets/24b59be1-11f0-484b-b10d-4b925c2a2cd7)
![image](https://github.com/user-attachments/assets/1492337b-2855-4f48-a8f4-b83337d3b031)

**Comment by thinkall** [comment]
Hi @albas99 , it seems that you're using flaml with python 3.12, which is not supported.

**Comment by albas99** [comment]
@thinkall oh, okay. That explains the strange behavior, because when I using it on Kaggle it was working just fine. I did find a workaround however by importing like this `from flaml.automl.automl import AutoML`.
