### ISSUE TITLE
[Issue]: Lack of Testing Around Reproducibility of Results of Classification and Regression Models

### ISSUE THREAD

**Issue by dannycg1996** [microsoft/FLAML#1361]
Hi all,

I've noticed that there are few FLAML issues centred on reproducibility. That is, if we take the best model which FLAML provides us with (`automl.model`), and retrain and test it on the same folds - we cannot always replicate the results. 
Could we create some unit tests around this? I had a quick glance through the codebase, and as far as I can tell, such tests don't currently exist.

I propose creating unit tests to verify the reproducibility of all in-built FLAML classification and regression models. An example of such a test for a CatBoostClassifier would be as follows:

1. Take an SKLearn dataset, such as the breast cancer dataset. Fix the resampling strategy to be cross-validation (CV), and restrict the estimators to only be catboost. Run it for say, 5 iterations. Run an AutoML instance with that configuration.
2. Take the best model which FLAML finds (which will be a CatBoostEstimator), and replicate the CV process i.e. train and test it on the exact same CV folds.
3. Assert that the reproduced score matches that provided by FLAML (using `pytest.approx`).
4. Repeat steps 2 and 3 with the underlying (i.e. the non FLAMLised model, `automl.model.model`), in this case a CatBoostClassifier.

To explain step 4, I'm making the assumption here that when fitted to the same folds, a FLAMLised model should produce identical results to the underlying SKLearn/CatBoost/XGBoost model. In my experience the two do not always return different results, as values are incorrectly mapped between them.

Based on of the currently open FLAML issues, quite a few of these tests would initially fail. I would initially comment such tests out. My intention with this issue is to be able to identify which models have issues, not to fix all reproducibility issues. Then in future, as reproducibility issues get fixed, the previously failing tests (which now pass) can be uncommented and made live. If they fail in future, we know that a bug has been introduced into the codebase. 

I should probably add that I'm happy to open a PR for this :)

I welcome any thoughts on the above - thanks all!

**Comment by thinkall** [comment]
Thank you @dannycg1996 . Please go ahead with your proposal.
