### ISSUE TITLE
[Bug]: fit terminated unexpected

### ISSUE THREAD

**Issue by yuhorun** [microsoft/FLAML#1380]
### Describe the bug

在使用flaml微调Lightgbm时，迭代53次后，异常终止。我试了2台电脑都是这样，能告诉我是什么原因么？

relation discussions @ #//[https://github.com/microsoft/FLAML/discussions/351](url)

## 我的代码：
settings = {
    "time_budget": 60*60*6,
    # "max_iter":60,
    "metric": "ap", 
    "estimator_list": ["lgbm"],
    "task": "classification",
    "log_file_name": "houses_experiment.log",
    "seed": 7654321,
    # "early_stop": True,
    "eval_method": "cv",
    "n_splits": 3,
}
sample_weight = compute_sample_weight(class_weight='balanced', y=Y)
automl.fit(X_train=X, y_train=Y, sample_weight=sample_weight, **settings)

### Model Used

lgbm

## 终端输出：
[flaml.automl.logger: 11-19 16:16:21] {2442} INFO -  at 7700.8s,        estimator lgbm's best error=0.2615,   best estimator lgbm's best error=0.2615
[flaml.automl.logger: 11-19 16:16:21] {2258} INFO - iteration 51, current learner lgbm
[flaml.automl.logger: 11-19 16:22:17] {2442} INFO -  at 8056.2s,        estimator lgbm's best error=0.2615,   best estimator lgbm's best error=0.2615
[flaml.automl.logger: 11-19 16:22:17] {2258} INFO - iteration 52, current learner lgbm
[flaml.automl.logger: 11-19 16:31:08] {2442} INFO -  at 8587.5s,        estimator lgbm's best error=0.2615,   best estimator lgbm's best error=0.2615
[flaml.automl.logger: 11-19 16:31:08] {2258} INFO - iteration 53, current learner lgbm

C:\Users\yuhor\Desktop\lgbm>

**Comment by thinkall** [comment]
@yuhorun , 可能是内存不够导致的。你可以监控一下训练过程中的内存变化吗？谢谢。

**Comment by yuhorun** [comment]
> [@yuhorun](https://github.com/yuhorun) , 可能是内存不够导致的。你可以监控一下训练过程中的内存变化吗？谢谢。

谢谢，我的问题已经解决。在异常终止前的的时刻，内存迅速占满，我把n_estimators调低后，已经能够正常训练。
