### ISSUE TITLE
Unable to train with ensemble option

### ISSUE THREAD

**Issue by dsbyprateekg** [microsoft/FLAML#139]
Thanks, Authors for your wonderful work.
[ensemble_logs.txt](https://github.com/microsoft/FLAML/files/6893865/ensemble_logs.txt)

I was trying this on a dataset and with individual estimators, the training part is done successfully but once I set the estimator_list in settings and set the ensemble option True like below-
`automl.fit(X_train=X_train, y_train=y_train, ensemble=True, **settings)`

I am getting following error- `ValueError: could not convert string to float: 'Yes'` at this line `automl.fit(X_train=X_train, y_train=y_train, ensemble=True, **settings)`

I am attaching complete logs for your reference. 

Let me know if you need my colab notebook or dataset to solve this issue.

**Comment by sonichi** [comment]
Hi @dsbyprateekg could you try installing the latest version `pip install flaml==0.5.10`? If it doesn't fix it, could you please share the notebook?

**Comment by dsbyprateekg** [comment]
@sonichi Thanks! With the latest version issue is resolved. I am able to train successfully. 
With this note I am closing this issue.
