### ISSUE TITLE
Apple Silicon M1 arm64 support

### ISSUE THREAD

**Issue by zzheng93** [microsoft/FLAML#140]
Hello,
Thank you for developing this tool. Very helpful. I attempted to install it on my local machine (MacBook Pro M1 with arm64) but failed. I think the main reason is that the catboost doesn't support the architecture  https://github.com/catboost/catboost/issues/1526. 
I wonder if there is any solution available? Or how to install FLAML without catboost? 
Thanks!

**Comment by qingyun-wu** [comment]
Hi @zzheng93, thank you for your interest. Are you using (or have you tried) [anaconda](https://www.anaconda.com/products/individual#macos) or miniconda (or [miniforge](https://github.com/conda-forge/miniforge) which  )to set up your development environment? If not, please try them. I (also using a machine with Apple Silicon M1 arm64) can install FLAML properly with a anaconda environment without issue in installing, importing, and using catboost.  Please give it a try if haven't tried these and let me know if you still have problems in installing FLAML. Thank you!

**Comment by zzheng93** [comment]
> Hi @zzheng93, thank you for your interest. Are you using (or have you tried) [anaconda](https://www.anaconda.com/products/individual#macos) or miniconda (or [miniforge](https://github.com/conda-forge/miniforge) )to set up your development environment? If not, please try them. I (also using a machine with Apple Silicon M1 arm64) can install FLAML properly with a anaconda environment without issue in installing, importing, and using catboost. Please give it a try if haven't tried these and let me know if you still have problems in installing FLAML. Thank you!

Hi @qingyun-wu , thank you very much for your kind reply. Yes, I used both miniconda and miniforge but failed. Would you please share the `environment.yml` that you used to install flaml?

Thank you!

**Comment by qingyun-wu** [comment]
Please find my [environment.yml](https://www.dropbox.com/s/b5rthq2fgk8r2kw/environment.yml?dl=0). Thank you!

**Comment by zzheng93** [comment]
Hi @qingyun-wu , thank you! 
It seems that your environment doesn't work for "Miniforge3-MacOSX-arm64" (the experimental conda-forge macOS ARM64 distribution). 
It works when I use "Miniforge3-MacOSX-x86_64" (an x86-64 Python distribution) with Rosetta2.
Would be great to know when the macOS ARM64 distribution is available.

reference: https://www.anaconda.com/blog/apple-silicon-transition
