### ISSUE TITLE
Could you create a R library, too?

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#15]
Hi Chi

Amazing work! Could you create a R library for it, too? There is still a large portion of potential users working in R.

Best,

**Comment by sonichi** [comment]
There seem to be a few ways to use Python code in R, or port models trained in Python to R. 

https://rstudio.github.io/reticulate/
https://stackoverflow.com/questions/61663184/porting-xgboost-model-between-python-and-r

Would that work for you?

**Comment by flippercy** [comment]
Hi Chi:

Thank you for your advice!

I am aware of reticulate and the post on porting xgboost models between python and R is a good eye-opener; however, from the perspective of consistency and scalability, it would still be better if there is a native R library of FLAML, even one simply using python cores sugar-coated with R by reticulate.  Sometimes it is harder to maintain and promote a bilingual modeling workflow, especially when it is supposed to be automatized like an assembly line.

I will test FLAML with reticulate after the vacation. Appreciate your response!

Best,
