### ISSUE TITLE
AttributeError: 'ConcurrencyLimiter' object has no attribute 'set_search_properties'

### ISSUE THREAD

**Issue by hanhanwu** [microsoft/FLAML#153]
### Discussed in https://github.com/microsoft/FLAML/discussions/152

<div type='discussions-op-text'>

<sup>Originally posted by **hanhanwu** August  6, 2021</sup>
I tried multiple dataset but always got error saying, "AttributeError: 'ConcurrencyLimiter' object has no attribute 'set_search_properties'"

Then I tried the simple 2 examples FLAML provided here: https://github.com/microsoft/FLAML, the iris and boston examples, same error. 
![WTF](https://user-images.githubusercontent.com/4024769/128588193-2bc5169e-b570-4fd4-9e64-2b8554fe46b1.PNG)

I have also tried some settings related to ConcurrencyLimiter, none worked.

Do you know how to fix this issue?

</div>

**Comment by qingyun-wu** [comment]
Hi @hanhanwu, can you please let me what tests are you running or the code you used to run this exp? And which version of flaml are you using? Thank you!

**Comment by hanhanwu** [comment]
Hi @qingyun-wu, I'm using the latest version v0.5.11.

Even when I was running the exact same example you guys were showing on the home page, this error happens.
Here's one of the examples I tried
![error](https://user-images.githubusercontent.com/4024769/128604625-f72866ac-ad16-4927-a5a0-beffc2564f26.PNG)

**Comment by qingyun-wu** [comment]
Hi @hanhanwu, unfortunately, I am not able to reproduce the error you had. Did you install ray? If so, what is the version? FLAML's required ray version is 1.5.1. 

Thanks!

**Comment by hanhanwu** [comment]
Oh, now it works. Forgot to install Ray. Thank you!

**Comment by sonichi** [comment]
@hanhanwu The example is supposed to work without ray installation. Did you use `pip install flaml` to install flaml?

**Comment by hanhanwu** [comment]
@sonichi Yes I did install FLAML in that way, but always had that error. Only after I have installed latest Ray, the error were gone. And "ConcurrencyLimiter" related error is mainly due to Tune, which is related to Ray
