### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by dsbyprateekg** [microsoft/FLAML#156]
Hi,

Since today I am getting below error while training the model-
`
AttributeError                            Traceback (most recent call last)
<ipython-input-12-5a5472c0ce3c> in <module>()
    119 }
    120 np.random.seed(2021)
--> 121 automl.fit(X_train=X_train, y_train=y_train, ensemble=True, **settings)
    122 print('Best ML leaner:', automl.best_estimator)
    123 print('Best hyperparmeter config:', automl.best_config)

8 frames
/usr/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

AttributeError: 'NoneType' object has no attribute 'predict_proba'
`
I am attaching here my notebook and dataset to reproduce the error-
[predict_genetic_disorder_ensemble.txt](https://github.com/microsoft/FLAML/files/6954376/predict_genetic_disorder_ensemble.txt)
[train.csv](https://github.com/microsoft/FLAML/files/6954420/train.csv)

Although the same notebook was running fine till yesterday.
Let me know if I am doing anything wrong here.

**Comment by qingyun-wu** [comment]
Hi @dsbyprateekg, What time budget do you use? I guess your time budget is not enough for FLAML to finish training a single model. So the output model is None. You may consider increasing your time budget. 

Thanks!

**Comment by qingyun-wu** [comment]
Hi @dsbyprateekg, we did some debug and it turns out the error is caused by the data pre-processing for catboost

```
 Invalid type for cat_feature category for [feature_idx=7]=1.0 : cat_features must be integer or string, real number values and NaN values should be converted to string.
``` 

We will try to handle the pre-processing error in the next release. There are several workaround you can use for now:
Option 1. Do the pre-processing yourself to resolve the format issue in your data column 'Parental consent' (make it to int or string)

Option 2. Remove the estimator 'catboost' from your ```estimator_list``` used in FLAML.

Thanks!

**Comment by dsbyprateekg** [comment]
Hi @qingyun-wu ,

Thanks for debugging the issue. 
With option2, I am able to proceed.
It's a mistake from my side that I have ignored this column and have not done the preprocessing.

**Comment by dsbyprateekg** [comment]
Thanks @sonichi , with this new version 0.5.12, this error is resolved.
