### ISSUE TITLE
How to enforce monotonicity in FLAML?

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#16]
Hi Chi:

Thank you for the cool work! Could I enforce monotonicity in the main automl.fit() function? If so, what algorithms can be chosen in the estimator list?

Best,

**Comment by sonichi** [comment]
What's the definition of monotonicity? Assuming the data has only one feature x and requiring the model prediction as a monotonic function of x?

**Comment by flippercy** [comment]
Yes. Ideally it would work as the monotone_constraints in xgboost.

**Comment by sonichi** [comment]
It's easy to add your custom XGBoost learner by inheriting the class XGBoostEstimator (regression) or XGBoostSklearnEstimator (classification) from flaml.model. See section 3 of the [notebook](https://github.com/microsoft/FLAML/blob/main/notebook/flaml_demo.ipynb) as an example.

In the constructor of the inherited estimator, set the monotonicity constraint you want to use in self.params, 
after calling `super().__init__()`.  For example, for regression, use

`class MonotonicXGBoostEstimator(XGBoostEstimator):`

`----def __init__(self, **params):`
`--------super().__init__(**params)`
`--------self.params["monotone_constraints"] = "(1,-1)"`

**Comment by flippercy** [comment]
Thank you for the response!

One extra question: it seems that the goal of automl is to fit the best ML model rather than mere hyperparameter tuning, is there any plan to also test and return ensembles of base models built during the search (such as a linear ensemble of the best model of each algorithm) ?

Best,

**Comment by sonichi** [comment]
You can set `ensemble=True` in the fit() function. It will build a stacked ensemble using the best models. 

Please let me know if that works for you. Thanks.

**Comment by flippercy** [comment]
It does. Thank you! For other questions, I will open a separate issue.
