### ISSUE TITLE
How to specify cat_features for the catboost learner?

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#161]
Hi:

I am using a customized catboost learner but having difficulties in specifying cat_features. 

The codes for the customized learner is:

from catboost import CatBoostClassifier

class MyMonotonicCatboostClassifier(BaseEstimator):

    def __init__(self, task = binary:logistic', thread_count = num_cores,  **params):

        super().__init__(task, **params)

        self.estimator_class = CatBoostClassifier

        # convert to int for integer hyperparameters
        self.params = {
            'verbose': False,
            'thread_count': params['thread_count'] if 'thread_count' in params else num_cores,
            'learning_rate': params['learning_rate'],
            'bagging_temperature': int(params['bagging_temperature']),
            'max_depth': int(params['max_depth']),
            'reg_lambda': params['reg_lambda'],
            'min_data_in_leaf': int(params['min_data_in_leaf']),
            'subsample': params['subsample'],
            'colsample_bylevel':params['colsample_bylevel'],
            'n_estimators':int(params['n_estimators']),
            'random_seed': params['random_seed'] if 'random_seed' in params else randomseed,
            "monotone_constraints":params['monotone_constraints'] if 'monotone_constraints' in params else monotone_catboost,   
       }  

If I use CatBoostEstimator from flaml.model as the class, cat_features can be specified in params; however, the final model lost the portability, which means that it cannot be saved by save_model() and ported into R.

If I set the class as self.estimator_class = CatBoostClassifier, I kept getting an error message stating that cat_features is missing. 

I am running the codes above in R via reticulate; not sure whether it is related.

Appreciate your help!

Thank you.

**Comment by sonichi** [comment]
>If I use CatBoostEstimator from flaml.model as the class, cat_features can be specified in params; however, the final model lost the portability, which means that it cannot be saved by save_model() and ported into R.
Why can't it be saved by save_model() and how does your customized learner solve that problem?

**Comment by flippercy** [comment]
Sorry, the issue has been resolved.

Appreciate your reply!

**Comment by sonichi** [comment]
You can set the cat_features in the same way as in flaml:
https://github.com/microsoft/FLAML/blob/10082b9262a862ef51cf09117bc5d13e43d1ca0d/flaml/model.py#L720-L724

**Comment by flippercy** [comment]
Thank you @sonichi; I will try.

On the other hand, is there any plan to expand the search space of catboost as discussed in #144 ?

**Comment by sonichi** [comment]
@stepthom is exploring it. @AlgoAIBoss made some suggestions in that thread. I'll be curious what’s a good search space for catboost. Maybe you can discuss on gitter with them and share with each other what you found. If you have a recommended search space, we can run some benchmark experiments to verify its effectiveness.

**Comment by flippercy** [comment]
Got it. Thank you very much!
