### ISSUE TITLE
Does it work with weighted datasets?

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#17]
Hi Dr. Wang:

Does this algorithm work with weighted datasets? I haven't seen any parameter like 'sample_weight'. Or shall I create customized learners for weighted datasets as you suggested for monotonicity?

Thank you.

**Comment by flippercy** [comment]
Any updates? Thank you!

**Comment by flippercy** [comment]
Thank you!

**Comment by sonichi** [comment]
You can use a class inherited from an existing learner, and override its [_fit()](https://github.com/microsoft/FLAML/blob/53e300ae02e38ae024c56679605b1c7709575891/flaml/model.py#L60) function. Replace `model.fit(X_train, y_train)` with `model.fit(X_train, y_train, sample_weight=w)`.

**Comment by flippercy** [comment]
Got it. Thank you for your patience!

**Comment by flippercy** [comment]
Hi Dr. Wang:

Below are some sample codes I wrote for a customized xgboost learner. The goal is to enable both weights and monotonicity.

class MyMonotonicXGBGBTreeClassifier(BaseEstimator):

   # search space
    params_configsearch_info = {
        'learning_rate': ConfigSearchInfo(name = 'learning_rate', type = float, lower = 0.01, init = 0.3, upper = 10),
        'gamma': ConfigSearchInfo(name = 'gamma', type = float, lower = 0, init = 0.0001, upper = 0.001),
        'max_depth': ConfigSearchInfo(name = 'max_depth', type = int, lower = 3, init = 6, upper = 20),
        'min_child_weight': ConfigSearchInfo(name = 'min_child_weight', type = int, lower = 1, init = 100, upper = 10000),
        'subsample': ConfigSearchInfo(name = 'subsample', type = float, lower = 0.33, init = 0.67, upper = 1),
        'colsample_bylevel': ConfigSearchInfo(name = 'colsample_bylevel', type = float, lower = 0.5, init = 0.75, upper = 1),
        'n_estimators': ConfigSearchInfo(name = 'n_estimators', type = int, lower = 50, init = 100, upper = 500)
    }

    
    def __init__(self, objective_name = 'binary:logistic', n_jobs = 10, learning_rate=0.3,
                gamma=0.0001, max_depth=6, min_child_weight=100, subsample=0.67, colsample_bylevel=0.75, n_estimators=100):

     super().__init__(objective_name = 'binary:logistic', n_jobs = 10, learning_rate=0.3,
                gamma=0.0001, max_depth=6, min_child_weight=100, subsample=0.67, colsample_bylevel=0.75, n_estimators=100)
    
     self.objective_name = objective_name

     self.estimator_class = XGBClassifier

     self.params = {
            'booster':'gbtree',
            'learning_rate': learning_rate,
            'gamma': gamma,
            'max_depth': int(round(max_depth)),
            'min_child_weight': int(round(min_child_weight)),
            'subsample': subsample,
            'colsample_bylevel':colsample_bylevel,
            'n_estimators':int(round(n_estimators)),
            "monotone_constraints":"(1, 0, -1, 0, 1, 1, 0)"
    }
        
    def _fit(self, X_train, y_train, sample_weight):    

        curent_time = time.time()
        X_train = self.preprocess(X_train)
        model = self.estimator_class(**self.params)
        model.fit(X_train, y_train, sample_weight)
        train_time =  time.time() - curent_time
        self.model = model
        return train_time

The codes ran well without the revised _fit function with sample_weight; however, after adding that part, I got an error as below:

    **11 '''The main flaml automl API'''
---> 12 automl.fit(X_train = X_train, y_train = y_train, sample_weight=w, **settings)

TypeError: fit() got an unexpected keyword argument 'sample_weight'**

What did I do wrong? Sorry, relatively new to python!

**Comment by sonichi** [comment]
`sample_weight` is not a keyword argument in the fit() function of AutoML, neither the _fit() function of a learner. So the sample_weight needs to be loaded from the customized learner class. That's not an ideal solution. But if you want to do a quick test, you can set `sample_weight=...` after `class MyMonotonicXGBGBTreeClassifier(BaseEstimator):`. And then in the _fit() funciton, remove `sample_weight` from the definition, and use `model.fit(X_train, y_train, sample_weight=self.sample_weight`).

We should add a sample_weight option in the fit() function of AutoML in the next version. 

BTW, you missed `n_jobs` in `self.params`.

**Comment by flippercy** [comment]
Thank you! I will try it next week.

Sent from my iPhone

On Jan 23, 2021, at 12:29 AM, Chi Wang <notifications@github.com> wrote:

﻿

sample_weight is not a keyword argument in the fit() function of AutoML, neither the _fit() function of a learner. So the sample_weight needs to be loaded from the customized learner class. That's not an ideal solution. But if you want to do a quick test, you can set sample_weight=... after class MyMonotonicXGBGBTreeClassifier(BaseEstimator):. And then in the _fit() funciton, remove sample_weight from the definition, and use model.fit(X_train, y_train, sample_weight=self.sample_weight).

We should add a sample_weight option in the fit() function of AutoML in the next version.

BTW, you missed n_jobs in self.params.
