### ISSUE TITLE
feature importance

### ISSUE THREAD

**Issue by hadisotudeh** [microsoft/FLAML#193]
Hi,

How can i get feature_importances_ of the tree-based models?

**Comment by sonichi** [comment]
You can use `automl.model.estimator.feature_importances_` to get the feature_importances_ for the best model found by automl.
If you want to get that for a particular estimator, for example lgbm, you can use `automl.best_model_for_estimator['lgbm'].estimator.feature_importances_`.

**Comment by knoam** [comment]
Would you consider doing permutation importance as well?

**Comment by ThakurRajAnand** [comment]
@sonichi Is there a way to get SHAP or LIME explanations for every prediction?

**Comment by sonichi** [comment]
@ThakurRajAnand Try [azureml-interpret](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-machine-learning-interpretability-aml)
@knoam You can use [sklearn.inspection.permutation_importance](https://scikit-learn.org/stable/modules/generated/sklearn.inspection.permutation_importance.html) on `automl.model.estimator` or `automl.best_model_for_estimator['lgbm'].estimator` etc.

**Comment by dyq0811** [comment]
> You can use `automl.model.estimator.feature_importances_` to get the feature_importances_ for the best model found by automl. If you want to get that for a particular estimator, for example lgbm, you can use `automl.best_model_for_estimator['lgbm'].estimator.feature_importances_`.

How to get corresponding feature names for these importance values?
