### ISSUE TITLE
What is log_max_bin?

### ISSUE THREAD

**Issue by thanhmannguyen3158** [microsoft/FLAML#199]
It seems like this param does not exist in LGBMRegressor or any ensemble models.

**Comment by sonichi** [comment]
It's the log transformed max_bin. It will be converted to max_bin before passing to LGBMRegressor.

**Comment by torronen** [comment]
I could not find the conversion from source for some reason, but based on other documentation I think it can be converted like:
` max_bin = 2^log_max_bin - 1 `

Let me know if I am mistaken.

**Comment by torronen** [comment]
In case someone else wonders, here is the conversion:

https://github.com/microsoft/FLAML/blob/81f54026c94312557a3e258c3073ede63fbb35be/flaml/model.py#L836
`   params["max_bin"] = (1 << params.pop("log_max_bin")) - 1`
