### ISSUE TITLE
Data cleaning/preparation for Numpy matrix input

### ISSUE THREAD

**Issue by ekzhu** [microsoft/FLAML#2]
Currently `pandas.Dataframe` input is [cleaned](https://github.com/microsoft/FLAML/blob/main/flaml/util.py#L284). 

Consider perform the same preparation steps for `numpy.ndarray` inputs.

**Comment by frsrgrrw** [comment]
I'd quite like to take on this request as my first contribution to an open-source project but not sure what exactly you're wanting - the link above is dead.

**Comment by sonichi** [comment]
Thanks for helping, @frsrgrrw. The link should be updated as: https://github.com/microsoft/FLAML/blob/d18d292081dbf34ffb2b1e3948acaf37569ebedd/flaml/data.py#L185

Fixing this issue should only require changes to `fit_transform()` and `transform()` in this file.

**Comment by Isha307** [comment]
@sonichi Can I work on this issue?

**Comment by bnriiitb** [comment]
@sonichi I would like to take this up

**Comment by bnriiitb** [comment]
> Currently `pandas.Dataframe` input is [cleaned](https://github.com/microsoft/FLAML/blob/main/flaml/util.py#L284).
> 
> Consider perform the same preparation steps for `numpy.ndarray` inputs.

the above mentioned link is dead. Could you please the updated one?

**Comment by sonichi** [comment]
> Thanks for helping, @frsrgrrw. The link should be updated as:
> 
> https://github.com/microsoft/FLAML/blob/d18d292081dbf34ffb2b1e3948acaf37569ebedd/flaml/data.py#L185
> 
> Fixing this issue should only require changes to `fit_transform()` and `transform()` in this file.

Please see my comment above.

**Comment by sonichi** [comment]
I found a recent technique that can be used to infer feature types automatically: https://github.com/pvn25/ML-Data-Prep-Zoo/tree/master/MLFeatureTypeInference
Any volunteer to try it in flaml?
