### ISSUE TITLE
Examples: Learning to rank - AssertionError

### ISSUE THREAD

**Issue by JosephKarpinski** [microsoft/FLAML#200]
Python 3.8.5
<img width="1223" alt="Error1" src="https://user-images.githubusercontent.com/37123616/132952060-aa719136-d79e-44c5-b333-9f73a38ff12e.png">
<img width="1556" alt="Error2" src="https://user-images.githubusercontent.com/37123616/132952062-440bb1f6-0c55-4da7-ae83-3a8536399cd5.png">

Examples: Learning to rank from URL https://github.com/microsoft/FLAML generates
AssertionError: # rows in X_train must match length of y_train.
See attached

**Comment by sonichi** [comment]
Thanks. Fixing it:
```python
from sklearn.datasets import fetch_openml
from flaml import AutoML
X_train, y_train = fetch_openml(name="credit-g", return_X_y=True, as_frame=False)
y_train = y_train.cat.codes
# not a real learning to rank dataaset
groups = [200] * 4 + [100] * 2    # group counts
automl = AutoML()
automl.fit(
    X_train, y_train, groups=groups,
    task='rank', time_budget=10,    # in seconds
)
```
