### ISSUE TITLE
Could we pass an argument for folds to automl.fit()?

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#203]
Hi @sonichi:

Is it possible to enable users to use a list of pre-defined CV folds (as most ML algorithms do) for automl.fit(), please? This feature is crucial when users want to create an ensemble with models returned by FLAML and models from other resources using cross-validation predictions directly.

 Thank you.

**Comment by sonichi** [comment]
What about taking the best model from automl after automl.fit(), and then using that model `automl.model` to build ensemble?

**Comment by flippercy** [comment]
Hi @sonichi:

Thank you for the reply.

On the one hand, with your advice above, will I be able to add models built by algorithms not compatible with sklearn API, such as splitGLM (https://github.com/cran/SplitGLM), which is even not available in python so far, to the ensemble?

On the other hand, I think the CV folds are assigned randomly during the search by FLAML (correct me if I am wrong); as a result, without a pre-defined CV folds the user won't be able to build an ensemble based on **CV predictions**; the model prediction on the training data is always available but my concern is that sometimes it will result in overfitting for the ensemble.

Best,

**Comment by sonichi** [comment]
Could you let me know how you build the ensemble without FLAML? I do not fully understand the questions. If you can already build the ensemble without FLAML, the only change with FLAML is you can use the best model found by FLAML to replace your original untuned model.

**Comment by flippercy** [comment]
Hi @sonichi:

Sorry for the confusion. 

To build an ensemble without FLAML, we usually create a bunch of cross-validated base learners first and then use the cross-validation prediction of each base learner as the training dataset for the meta learner. To do that, we also have to use the same pre-defined CV folds for all the base learners so that their cross validation predictions can be combined.

Do you think I can do the same with models returned by FLAML currently? If so please advise.

Thank you.

**Comment by sonichi** [comment]
Yes. First, run flaml as usual. Second, use the best model(s) from flaml as the base learner(s), and start building your ensemble. Basically, take the model(s) from flaml as your start point of base learners.

**Comment by flippercy** [comment]
How about cross validation predictions? Are they part of the FLAML output or do I have to calculate them separately?

**Comment by sonichi** [comment]
The same way as you get cross validation predictions today for your base learners when not using flaml.

**Comment by flippercy** [comment]
Close it for now; will check whether it works with the current pipeline for stacked ensemble.

Thank you.
