### ISSUE TITLE
'SearchState' object has no attribute 'trained_estimator'

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#205]
Hi @sonichi:

When running the latest version of FLAML (0.6.2) on an azure VM via reticulate, I got the following error:

>>> automl._search_states['MonoLightGBM'].trained_estimator
AttributeError: 'SearchState' object has no attribute 'trained_estimator'

As a result, automl.best_model_for_estimator('MonoLightGBM') returned an empty object.

However, this learner has been searched thoroughly by FLAML:

>>> automl._search_states['MonoLightGBM'].total_iter
199

Any idea on why I got this error? It did not happen with older versions

Thank you.

**Comment by sonichi** [comment]
Please pass "keep_search_state=True" to AutoML.fit()? Otherwise, the big objects in search states are cleared after fit finished for saving memory.

**Comment by flippercy** [comment]
Got it. Thank you!
