### ISSUE TITLE
How to specify lrl1 as the final estimator for the ensemble?

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#206]
Hi @sonichi:

I am wondering how to use lrl1 as the final estimator for the ensemble.  The codes below do not work.

"ensemble": {"final_estimator": 'lrl1',
                "passthrough": False,}

Thank you.

**Comment by sonichi** [comment]
`"final_estimator": 'lrl1',`
->
`"final_estimator": LRL1Classifier(**params),`
