### ISSUE TITLE
log error?

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/FLAML#221]
roc_auc???
![image](https://user-images.githubusercontent.com/20265321/134616276-266ad3a6-a283-4a8e-b28e-2ca1cbd2c285.png)

**Comment by qingyun-wu** [comment]
Hi @Jie-Yuan, be noted that the log is showing the error (or loss). When your metric is `roc_auc`, the error value is `1 - roc_auc`.  From your log attached, it seems the `roc_auc` score is 1.0, implying a perfect learner. Although not impossible, it is indeed rare. Can you please provide more information about your task or what exactly is your concern?

Thank you!

**Comment by qingyun-wu** [comment]
Hi @Jie-Yuan, I am closing this issue as I didn't hear from you for over a month. Please feel free to re-open it if you have further questions. Thank you!
