### ISSUE TITLE
Documentation question -- example for warm-start?

### ISSUE THREAD

**Issue by lokijota** [microsoft/FLAML#237]
Hi,

the docs for the latest version say this:

*"support warm-start in AutoML.fit() by using previously found start points."*

I found the notebook with the warm-start sample (`flaml_automl.ipynb`), but this seems to be more of specifying boundaries on a previously executed search (plus the code is complex), not a "search for 2 hours more" kind feature. 

Is there documentation on warm-start in addition to the notebook?

**Comment by sonichi** [comment]
Thanks for the question. We'll add more documentation about it. For warm-start the `AutoML.fit()`, please see one example below.
https://github.com/microsoft/FLAML/blob/a99e939404caeda88f32724cc264841f2f5dcfca/test/test_automl.py#L819-L846
For warm-start `tune.run`, please see one example below.
https://github.com/microsoft/FLAML/blob/a99e939404caeda88f32724cc264841f2f5dcfca/test/tune/test_tune.py#L226-L247

**Comment by qingyun-wu** [comment]
Hi @lokijota,

Thank you for your question. I created a PR for the documentation of warm-start related arguments (`starting_points` for `AutoML.fit()` and `evaluated_rewards` for  `tune.run()`), where you can find simple code examples (basically the ones mentioned by @sonichi) and you also can find a brief explanation for those args.  

Please let me know if your question is resolved or not. Thank you!
