### ISSUE TITLE
Hang or segfault with Python 3.9 MacOS conda

### ISSUE THREAD

**Issue by cdeil** [microsoft/FLAML#243]
I'm using this:
```
 % cat case_study/environment.yml 
name: cement

channels:
- conda-forge
- nodefaults

dependencies:
- python==3.9
- jupyterlab==3.1
- pandas==1.3
- scikit-learn==1.0
- missingno
- matplotlib
- seaborn==0.11
- dtale==1.56
- pandas-profiling
- sweetviz==2.1
- pip
- pip:
    - flaml
```
and
```
conda env create -f environment.yml
```

and then trying to execute the hello-word regression example in the README I get a hang from JupyterLab or a segfault from ipython:

```
[flaml.automl: 10-05 19:28:26] {1432} INFO - Evaluation method: cv
[flaml.automl: 10-05 19:28:26] {1478} INFO - Minimizing error metric: 1-r2
[flaml.automl: 10-05 19:28:26] {1515} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'catboost', 'xgboost', 'extra_tree']
[flaml.automl: 10-05 19:28:26] {1748} INFO - iteration 0, current learner lgbm
zsh: segmentation fault  ipython
```

I didn't try to debug this or other versions, it worked a month ago on Mac on Python 3.8.

Maybe you could extend your CI to also test with conda and try to reproduce / fix the issue?

**Comment by sonichi** [comment]
Could you follow https://github.com/microsoft/FLAML/issues/223#issuecomment-932356442?
We haven't been able to reproduce the problem but this debugging mode should help identifying the cause.

**Comment by cdeil** [comment]
Maybe you'll see the error if you add a MacOS conda build using the env I gave above to your CI?

**Comment by cdeil** [comment]
Reported here: https://github.com/microsoft/LightGBM/issues/4666
