### ISSUE TITLE
How to save model to disk for future using

### ISSUE THREAD

**Issue by keremtatlici** [microsoft/FLAML#265]
```
from flaml import AutoML
automl = AutoML()

automl_params = {
    'time_budget' : 60*5,
    'metric': 'rmse',
    'task': 'regression',
    'log_file_name': '../results/flaml_log.txt',
    'estimator_list': ['lgbm'],
    'n_jobs': -1,
    'model_history':True
}
automl.fit(
    X,
    Y,
    starting_points = automl.best_config_per_estimator,
    **automl_params
    )
```

I trained lgbm model like this but i want to save it to drive for future using. How can i do that ?

**Comment by qingyun-wu** [comment]
Hi @keremtatlici, you can just use pickle to dump the automl object and load it when you want to use it. You can find an example in this [notebook](https://github.com/microsoft/FLAML/blob/main/notebook/flaml_automl.ipynb) (In [7]). Let me know if your question is not resolved. Thank you!

**Comment by keremtatlici** [comment]
Thanks, it worked !
