### ISSUE TITLE
Is multi-tasking allowed?

### ISSUE THREAD

**Issue by miquelduranfrigola** [microsoft/FLAML#277]
Hi!

Many thanks for a very useful tool. I wonder if multi-output regression (multi-tasking) is allowed with FLAML. I know that, at least, CatBoost does allow for this option.

Many thanks in advance!
M

**Comment by sonichi** [comment]
@miquelduranfrigola If you already know how to use flaml for single-output regression, I sketched a way to use it for multi-output regression in #192. I haven't tried it myself. 
BTW, how many outputs do you need to fit simultaneously?

**Comment by miquelduranfrigola** [comment]
Thanks @sonichi! I typically fit 10-20 outputs, which means that the solution provided in #192 may be a bit slow, since at the end of the day multiple single-output regressors will have to be fit. But it will work for now! I will try it and let you know if I find any problem.

**Comment by sonichi** [comment]
@slhuang Please take a look at this use case. I think it's another motivating example.
