### ISSUE TITLE
A new error when fitting automl with X_val and y_val specified: 'TypeError: transform() takes 2 positional arguments but 3 were given'

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#278]
Hi FLAML team:

After upgrading the FLAML to the latest version, there is an error when I ran automl.fit() with X_val and y_val specified. Using your notebook on automl as an example:

from flaml.data import load_openml_dataset
X_train, X_test, y_train, y_test = load_openml_dataset(dataset_id=1169, data_dir='./')

from flaml import AutoML
automl = AutoML()

settings = {
    "time_budget": 240,  # total running time in seconds
    "metric": 'accuracy',  # can be: 'r2', 'rmse', 'mae', 'mse', 'accuracy', 'roc_auc', 'roc_auc_ovr',
                           # 'roc_auc_ovo', 'log_loss', 'mape', 'f1', 'ap', 'ndcg', 'micro_f1', 'macro_f1'
    "task": 'classification',  # task type
    "log_file_name": 'airlines_experiment.log',  # flaml log file
    "seed": 7654321,    # random seed
}

>>> automl.fit(X_train=X_train, y_train=y_train, X_val=X_test, y_val=y_test,**settings)
TypeError: transform() takes 2 positional arguments but 3 were given

Request if you could look into it.

Thank you!

**Comment by sonichi** [comment]
@flippercy Could you show me the trace of error? Thanks.

**Comment by flippercy** [comment]
Here you go.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_4757/550052602.py in <module>
----> 1 automl.fit(X_train=X_train, y_train=y_train, X_val=X_test, y_val=y_test, **settings)

~/.local/lib/python3.7/site-packages/flaml/automl.py in fit(self, X_train, y_train, dataframe, label, metric, task, n_jobs, log_file_name, estimator_list, time_budget, max_iter, sample, ensemble, eval_method, log_type, model_history, split_ratio, n_splits, log_training_metric, mem_thres, pred_time_limit, train_time_limit, X_val, y_val, sample_weight_val, groups_val, groups, verbose, retrain_full, split_type, learner_selector, hpo_method, starting_points, seed, n_concurrent_trials, keep_search_state, early_stop, append_log, auto_augment, min_sample_size, use_ray, **fit_kwargs)
   1468 
   1469         self._validate_data(
-> 1470             X_train, y_train, dataframe, label, X_val, y_val, groups_val, groups
   1471         )
   1472         self._search_states = {}  # key: estimator name; value: SearchState

~/.local/lib/python3.7/site-packages/flaml/automl.py in _validate_data(self, X_train_all, y_train_all, dataframe, label, X_val, y_val, groups_val, groups)
    589             if self._label_transformer:
    590                 self._state.y_val = self._label_transformer.transform(
--> 591                     y_val, self._state.task
    592                 )
    593             else:

TypeError: transform() takes 2 positional arguments but 3 were given

**Comment by sonichi** [comment]
Thanks. This problem has been fixed by #274 
You can either wait for the release of v0.7.1 or clone the latest version and do "pip install -e".

**Comment by sonichi** [comment]
Update: v0.7.1 is released.
