### ISSUE TITLE
'NoneType' object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by hadisotudeh** [microsoft/FLAML#296]
Hi,

Today, I faced the following issue:
![image](https://user-images.githubusercontent.com/2101643/142725703-e98a07d3-684b-467a-95b7-c8c22b2db8e8.png)
![image](https://user-images.githubusercontent.com/2101643/142725714-787fd2b4-0385-4147-9ce5-ce609e35768a.png)

I am using "pip install git+https://github.com/microsoft/FLAML.git" to install the library.

P.S. it also did not let me to use catboost, as it seems it was not installed!

**Comment by sonichi** [comment]
Could you set `verbose` to 3 and see if any model has been trained? The default time budget is 60s and if the preprocessing takes longer than that, no model will be trained. If that's the case, increase the time budget.
To use catboost, install flaml with the option [catboost].
`pip install git+https://github.com/microsoft/FLAML.git#egg=flaml[catboost]`

**Comment by hadisotudeh** [comment]
That is correct and it seems to be because of "time_budget". Maybe, this point can be added to the documentation.
