### ISSUE TITLE
Need some kind of ignorance

### ISSUE THREAD

**Issue by citron** [microsoft/FLAML#315]
Hello
In LightGBM, we can pass a dataframe with features marked as ignored by using the `"ignore_column"` option.
Is there a way to do the same in Flaml ?
This is very useful when one needs to keep track of records. Or did I miss something ?
Have a wonderful coding day !

**Comment by sonichi** [comment]
From [lightgbm doc](https://lightgbm.readthedocs.io/en/latest/Parameters.html): Note: works only in case of loading data directly from text file.
Not sure what is the use case you are thinking of. Could you elaborate more?

**Comment by citron** [comment]
I do use Flaml at the hospital emergency service. A CSV row is indexed by a unique "passage" number which allows us to relate measurement to patients. As the CSV is used in various pipelines and flows, it would be easier not to alter it to much. I do prefer to keep the "passage" numbers even If It should not be treated a feature.

**Comment by sonichi** [comment]
@citron For such columns with unique value for each row, flaml will automatically drop them during training and prediction. You can keep them in your data. Please let me know if it doesn't work.

**Comment by citron** [comment]
@sonichi I noticed that among my 350000 lines, I had 7 with the same "passage" numbers. That why Flaml saw this column as a category. Thanks for the help !
