### ISSUE TITLE
What exactly does pred_time_limit refer to?

### ISSUE THREAD

**Issue by EgorKraevTransferwise** [microsoft/FLAML#318]
`pred_time_limit` sounds like a great way to limit complexity of models being fitted; but what time does it refer to: inference on one row, inference on the whole training dataset, or something else?

**Comment by sonichi** [comment]
It refers to the average prediction time per row in validation data.
https://github.com/microsoft/FLAML/blob/85e21864ce20a323fefe297b18b8aa75f9a72f59/flaml/ml.py#L205
Adding it to docstr in #319

**Comment by EgorKraevTransferwise** [comment]
Thanks a lot! Where can I find some guidance as to reasonable values? Especially as I expect due to vectorization this doesn't scale linearly in dataset size.
