### ISSUE TITLE
Using 'gap' for time series cv in Flaml

### ISSUE THREAD

**Issue by tugra-alp** [microsoft/FLAML#329]
![9fb545ac-d898-43d4-b567-65ba33a2ed0b](https://user-images.githubusercontent.com/82160533/145007241-c057d53e-b2b1-44ff-82b5-3820b96bdbf2.jpg)

How can we use 'gap' method which is exist in sklearn.model_selection.TimeSeriesSplit in Flaml ? 

![6dc03571-ea29-427b-b3f7-fd92cd9cd717](https://user-images.githubusercontent.com/82160533/145007305-54d56e67-951c-474a-a8fd-f34012561933.jpg)

**Comment by slhuang** [comment]
Hello, we are currently working on a feature to allow customized splitters #238. You should be able to pass in `Gap` with this new feature. Stay tuned.

**Comment by tugra-alp** [comment]
Sorry , but I dont understand how i can set parameters of TimeSeriesSplit function in Flaml custom data splitter . Is there any use case example for that  ?
