### ISSUE TITLE
get_output_from_log returns empty objects

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#33]
Hi:

get_output_from_log returns empty objects for me with no error message:

from flaml.data import get_output_from_log
get_output_from_log(filename = 'test.log', time_budget = 600)

([], [], [], [], [])

However, when I ran your sample codes in the notebook, this function worked well. Moreover, my test log file exists and can be accessed in Jupyter using other methods.

I am using 0.2.5 and my settings are:

settings = {
    "time_budget": 3600 
    'eval_method':'cv',
    'max_iter' :100,
    'n_splits' :5,
    'log_type' :'all', 
    "metric": 'roc_auc', 
    "task": 'classification',   
    "log_file_name": 'test.log', 
    "log_training_metric": False
}

Any ideas?

Appreciate your help! So far the feedback of FLAML from our users is overwhelmingly positive. Great work!

**Comment by sonichi** [comment]
The first simple thing to check is whether you have any record finished before 600s. With `time_budget=600` it will look for records finished before that point.

**Comment by flippercy** [comment]
Silly me.....somehow I thought time_budget meant the amount of time allowed for this function to run.....

Thank you!
