### ISSUE TITLE
Write example test for using nni tuning interface

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#36]
add test/nni to illustrate how to use flaml in the nni framework.

**Comment by ImanHosseini** [comment]
I tried to use the _BlendSearchTuner_ in NNI, for the mnist case, I tried this config.yaml:
```yaml
authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  codeDir: /path/to/flaml/searcher/
  classFileName: blendsearch.py
  className: BlendSearchTuner
# The path and the running command of trial
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
```
But it crashes with this error:
```
[2021-03-13 15:04:12] ERROR (nni.main/MainThread) attempted relative import with no known parent package
Traceback (most recent call last):
  File "/home/iman/.local/lib/python3.8/site-packages/nni/__main__.py", line 108, in <module>
    main()
  File "/home/iman/.local/lib/python3.8/site-packages/nni/__main__.py", line 43, in main
    tuner = _create_tuner(exp_params)
  File "/home/iman/.local/lib/python3.8/site-packages/nni/__main__.py", line 87, in _create_tuner
    tuner = create_customized_class_instance(exp_params.get('tuner'))
  File "/home/iman/.local/lib/python3.8/site-packages/nni/tools/package_utils/__init__.py", line 200, in create_customized_class_instance
    class_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/salva/Documents/GitHub/FLAML/test/../flaml/searcher/blendsearch.py", line 17, in <module>
    from .search_thread import SearchThread
ImportError: attempted relative import with no known parent package
```
Is there another intended way to use the blendsearch tuner with NNI?

**Comment by ImanHosseini** [comment]
Ok, I found a way to make it work, but it is not pretty. To fix the import issue, I made a 'wrap.py':
```python
from flaml.searcher import blendsearch
BlendSearchTuner = blendsearch.BlendSearchTuner
```
and in config.yaml:
```yaml
tuner:
  codeDir: ./
  classFileName: wrap.py
  className: BlendSearchTuner
```
Now doing "nnictl create --config ./config.yaml" works. Will this be helpful to someone trying to use NNI with _BlendSearchTuner_? If it does, it is not _test_ -ish, maybe a markdown file describing it would be helpful documentation?

**Comment by sonichi** [comment]
Thanks @ImanHosseini. What about creating test/nni/ and putting the config.yaml and flaml_nni_wrap.py under it?
For flaml_nni_wrap.py, we can use:
`from flaml.searcher.blendsearch import BlendSearchTuner, CFO as CFOTuner`
After testing it, we can add an example to flaml/tune/README.md.
One issue to figure out is how to specify initial values corresponding to low cost for a subset of hp dimensions, which is important for both CFOTuner and BlendSearchTuner.

**Comment by ImanHosseini** [comment]
It is okay to just add the [mnist.py](https://github.com/microsoft/nni/blob/52e40cb89b5757b1616d3f561c75c36a3fd36674/test/ut/tools/annotation/testcase/usercode/mnist.py)  from the NNI sample right?
To pass initial value to the tuner, I do this in the wrapper:
```python
from flaml.searcher.blendsearch import BlendSearchTuner as BST, BlendSearch
class BlendSearchTuner(BST):
    def __init__(self, points_to_evaluate=[{"hidden_size":128}]):
        BlendSearch.__init__(self,points_to_evaluate=points_to_evaluate)
```
It works _here_ but for a general  case, one way would be to check the _known_ parameters, like: for _hidden_dimension_ or other _dimension_ (e.g. embedding dimension) parameters pick smallest, to known _low cost_ ones. 
But on _another_ point, I _think_ I found a bug: when I run _BlendSearchTuner_ I get this error: 
```
 ERROR (nni.runtime.msg_dispatcher_base/Thread-1) too many values to unpack (expected 2)
```
On this line: https://github.com/microsoft/FLAML/blob/ec37ae8f8fa3067c5bfe422d97632f469b747645/flaml/searcher/blendsearch.py#L445
due to the fact that _parameters_ is a dictionary (like: {'hidden_size': 128, 'batch_size': 32, 'lr': 0.1, 'momentum': 0.9800580891201499}) shouldn't that line be:
```python
            for key, value in parameters.items():
```
?

**Comment by sonichi** [comment]
Thanks. Yes it's a bug. Could you fix it in this PR?

It is okay to add the mnist.py from the NNI sample with a comment in the file marking the source.

And your way to pass points_to_evaluate is OK. One suggestion: use `super().__init__`.

**Comment by tanmay2798** [comment]
Hi, I had a question, there are cases when None is returned as configuration from suggest function of Blendsearch. So in that case, nni.get_next_parameter() receives None configuration. How can we handle that case?
