### ISSUE TITLE
test\nlp\test_autohf_summarization.py error with pytest

### ISSUE THREAD

**Issue by int-chaos** [microsoft/FLAML#360]
@liususan091219 

when running `pytest test` this error was prompted

![test_autohf_summarization error](https://user-images.githubusercontent.com/74878789/147369417-0532bf53-4edc-4941-b92d-4484d8179fed.png)

**Comment by liususan091219** [comment]
What's your transformers version? This happened to me when it was 4.5, need to make sure it's the latest version (4.14)

**Comment by int-chaos** [comment]
works now. thank you
