### ISSUE TITLE
Error " no current event loop in thread 'Thread-2" happen when param 'use_ray' is True

### ISSUE THREAD

**Issue by bladesaber** [microsoft/FLAML#363]
Hello, when I set the param use_ray to be True it will throw a Error: 
    "RuntimeError: There is no current event loop in thread 'Thread-2'.".

Below is the code I reproduce:
`
automl = AutoML()
automl_settings = {
    "time_budget": 5,  # in seconds
    "metric": 'r2',
    "task": 'regression',
    "log_file_name": "california.log",
    "use_ray": True,
    "estimator_list": ['xgboost', 'rf', 'extra_tree']
}
X_train, y_train = fetch_california_housing(return_X_y=True)
automl.fit(X_train=X_train, y_train=y_train, **automl_settings)
print(automl.model.estimator)
`

Looking forward to response, Thanks everyone. ^_^

**Comment by qingyun-wu** [comment]
Hi @bladesaber,

I cannot reproduce the error with the code provided. Which version of flaml are you using? I am using the latest version (v0.9.2). Can you try the latest version if you are not using it?

Thank you!

**Comment by bladesaber** [comment]
Strange. The version of flaml is also 0.9.2. I think may be the version of ray is non compatible, my ray is the latest version 1.9.1.

**Comment by qingyun-wu** [comment]
Maybe, can you try `ray[tune]==1.6.0`. I will try `1.9.1` as well. Thanks!

**Comment by qingyun-wu** [comment]
> Hello, when I set the param use_ray to be True it will throw a Error: "RuntimeError: There is no current event loop in thread 'Thread-2'.".
> 
> Below is the code I reproduce: `automl = AutoML() automl_settings = { "time_budget": 5, # in seconds "metric": 'r2', "task": 'regression', "log_file_name": "california.log", "use_ray": True, "estimator_list": ['xgboost', 'rf', 'extra_tree'] } X_train, y_train = fetch_california_housing(return_X_y=True) automl.fit(X_train=X_train, y_train=y_train, **automl_settings) print(automl.model.estimator)`
> 
> Looking forward to response, Thanks everyone. ^_^

Hi @bladesaber,

Could you share your full traceback? Thank you!

**Comment by qingyun-wu** [comment]
Hi @bladesaber,

In case you are still having this error: it might be because of the library `dast`. If you have a version of`dask` installed in your environment,  it may fail `lightgbm` if the version is not right and throw the error. In this case, you can try uninstalling `dask`. Let me know if you still need help. Thanks!

**Comment by bladesaber** [comment]
Yes, it works. Thanks
