### ISSUE TITLE
Add documentation for other NLP tasks

### ISSUE THREAD

**Issue by liususan091219** [microsoft/FLAML#374]
+ Multiple choice classification
+ Token classification
+ QA

**Comment by sonichi** [comment]
Places to check:

docstr for `task` in automl.py
"Tasks" in https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML
Examples in https://microsoft.github.io/FLAML/docs/Examples/AutoML-NLP
