### ISSUE TITLE
Verbose argument in model.fit()

### ISSUE THREAD

**Issue by rroy09** [microsoft/FLAML#38]
Hi,

While training the learner, a console output is generated, which can take up huge space in the notebook if the time_budget is made large. If I wish to suppress the console output while training my learner, how do I do that? In keras, sklearn, etc., setting verbose = 0 suppresses the console output.

Thanks!

**Comment by sonichi** [comment]
Thanks for the question. The easiest way to do it in your notebook now is to insert these two lines before `automl.fit()`:

`from flaml import logger`
`logger.setLevel(logging.WARNING)`

for example:
`from flaml import logger`
`logger.setLevel(logging.WARNING)`
`automl.fit(X_train = X_train, y_train = y_train, **settings)`

I'd also encourage a pull request to add an argument `verbose` in `automl.fit()`. Feel free to do it if you'd like to contribute.

**Comment by rroy09** [comment]
Thanks for the response. However, I get an error 'logging is not defined'.

**Comment by sonichi** [comment]
@rroy09 Please also add `import logging`.

**Comment by rroy09** [comment]
Thanks a lot for the response.
