### ISSUE TITLE
Do you expect FLAML to run across multiple nodes in AML using RAY

### ISSUE THREAD

**Issue by camer314** [microsoft/FLAML#393]
On your page [https://microsoft.github.io/FLAML/docs/Examples/Integrate%20-%20AzureML/#use-ray-to-distribute-across-a-cluster](url) you describe the process of configuring an AML cluster with Ray and using FLAML against it.

Is it your expectation that this configuration, as you have it, will be distributed Ray or parallel Ray on a single node?

I was under the impression you needed a compute cluster with a VNET to allow a Ray cluster?

Also I ran your sample and modified it slightly to log the node id of the machine executing (I did this via a custom metric so it ran for each iteration) and it always only logged the same node that my flaml script is executing on even though I have 2 nodes available.

**Comment by camer314** [comment]
After further testing I got this working as per your documentation :)

**Comment by sonichi** [comment]
Great to hear that! Looking forward to your feedback.

@ruizhuanguw @aminsaied @rezasherafat @qingyun-wu @slhuang

**Comment by camer314** [comment]
This works well. What do you know about this hidden environment variable _AZUREML_CR_START_RAY? Is this something that is reliable? Do you think the AML guys will make Ray initialize public anytime soon?

Also in the log files at the end there is a big table printed that has all the information for each trial, is that information available through the library?

**Comment by sonichi** [comment]
> This works well. What do you know about this hidden environment variable _AZUREML_CR_START_RAY? Is this something that is reliable? Do you think the AML guys will make Ray initialize public anytime soon?

@rezasherafat could you chime in here?
> 
> Also in the log files at the end there is a big table printed that has all the information for each trial, is that information available through the library?

The information for each trial is logged in a file, as documented [here](https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#log-the-trials). It is not exactly the same as the big table printed by ray. Let us know if the current logging works for you.

**Comment by rezasherafat** [comment]
the start ray variable is currently experimental, i.e., may change in the future.

**Comment by camer314** [comment]
Thanks @rezasherafat, it is an extremely handy piece of functionality so hoping it makes it to public

@sonichi With the log file and distribution, is the log file the composite of all nodes or is it just the log file from the master node (seems like I have only a subset in my log file from what Ray is reporting)

**Comment by sonichi** [comment]
@camer314 It logs the runs from all the nodes. But remember that by default it only logs trials that are better than previous trials. To log all the trials, pass `log_type="all"`.

**Comment by camer314** [comment]
Indeed it does, you are correct

This Ray stuff works really well, especially spread across the cluster.

**Comment by sonichi** [comment]
> Indeed it does, you are correct
> 
> This Ray stuff works really well, especially spread across the cluster.

Wonderful! Please keep us posted. BTW, what application do you use flaml for?

**Comment by camer314** [comment]
It is an application under development that allows distributed hyper parameter optimizations for our own internal GLM/GBM models + LGBM etc

The application is being demonstrated tomorrow to the Azure ML engineering team seeing as we work as partners with you guys. I am going to be pushing for the Ray setup to be promoted to public GA in AML.

Btw, if you want a demo of what we are doing and how we are using FLAML let me know in DM and can arrange that.
