### ISSUE TITLE
Forecasting example

### ISSUE THREAD

**Issue by Yasslight90** [microsoft/FLAML#412]
Hello,

The example on https://github.com/microsoft/FLAML for forecasting is not working with the latest release 0.9.5. Please find the error below:

InsufficientDataLengthError: Sum of model lags (3) and forecasting horizon (12 cannot be bigger than length of y (12).

Kind regards,

Yassine

**Comment by sonichi** [comment]
It looks a bug for the newly added regressors. @int-chaos 

As a workaround, you can limit the estimator_list to `["prophet", "arima", "sarimax"]`.

**Comment by Yasslight90** [comment]
I just came back to and old release. Let me know when you release a new version. 
Thank you!

**Comment by int-chaos** [comment]
Thank you for the issue. I'll look into it more, but it seems the error occurs because the lag value is too big.

**Comment by sonichi** [comment]
> I just came back to and old release. Let me know when you release a new version. Thank you!

@Yasslight90 v0.9.6 is released.

**Comment by Yasslight90** [comment]
Ok perfect. I will test it.
