### ISSUE TITLE
Unable to work with FLAML in Kaggle

### ISSUE THREAD

**Issue by GDGauravDutta** [microsoft/FLAML#433]
Error : 
IImportError                               Traceback (most recent call last)
/tmp/ipykernel_33/3768597154.py in <module>
----> 1 from flaml import AutoML
      2 automl = AutoML()

/opt/conda/lib/python3.7/site-packages/flaml/__init__.py in <module>
      1 from flaml.searcher import CFO, BlendSearch, FLOW2, BlendSearchTuner
----> 2 from flaml.automl import AutoML, logger_formatter
      3 from flaml.onlineml.autovw import AutoVW
      4 from flaml.version import __version__
      5 import logging

/opt/conda/lib/python3.7/site-packages/flaml/automl.py in <module>
     22 import logging
     23 import json
---> 24 from .ml import (
     25     compute_estimator,
     26     train_estimator,

/opt/conda/lib/python3.7/site-packages/flaml/ml.py in <module>
      6 import numpy as np
      7 import pandas as pd
----> 8 from sklearn.metrics import (
      9     mean_squared_error,
     10     r2_score,

ImportError: cannot import name 'mean_absolute_percentage_error' from 'sklearn.metrics' (/opt/conda/lib/python3.7/site-packages/sklearn/metrics/__init__.py)

**Comment by sonichi** [comment]
mean_absolute_percentage_error is only available from scikit-learn>=0.24.
Are you able to install scikit-learn>=0.24 in Kaggle?

**Comment by GDGauravDutta** [comment]
# Name                    Version                   Build  Channel
scikit-learn              1.0.2            py37hf9e9bfc_0    conda-forge

**Comment by sonichi** [comment]
No import error for me: https://www.kaggle.com/sonichi/notebooka80575f30b

**Comment by GDGauravDutta** [comment]
Not able to see your notebook

**Comment by sonichi** [comment]
> Not able to see your notebook

Could you try again now?

**Comment by GDGauravDutta** [comment]
still not working

**Comment by sonichi** [comment]
> still not working

Do you mean you still can't see my notebook? I've made it public and tested.

**Comment by GDGauravDutta** [comment]
> > still not working
> 
> Do you mean you still can't see my notebook? I've made it public and tested.

It's visible now

**Comment by GDGauravDutta** [comment]
I found that issue only appear only if pandas are imported first before Flaml

**Comment by sonichi** [comment]
> I found that issue only appear only if pandas are imported first before Flaml

It doesn't fail for me.
