### ISSUE TITLE
fit() got an unexpected keyword argument 'gpu_per_trial'

### ISSUE THREAD

**Issue by torronen** [microsoft/FLAML#435]
How would I go ahead debugging GPU issues?

When trying to run .fit with gpu_per_trial = 1, I receive the error "fit() got an unexpected keyword argument 'gpu_per_trial'"
I have installed Keras and Tensorflow support, and those are able to utilize the Nvidia card.

```
timebudget = 60 * 60
automl = AutoML()
                settings = {
                    "time_budget": timebudget, 
                    "metric": "accuracy",  
                    "estimator_list": ['lgbm'],  
                    "task": 'binary',  
                    "log_file_name": savepath + filename + '.log',  
                    "gpu_per_trial": 1,
                }
automl.fit(X_train=train_set, y_train=y_train, X_val=val_set, y_val=y_val, early_stop=True, **settings)
```

**Comment by torronen** [comment]
@sonichi ok, thanks. Both: now just testing. In future, probably GPU for LightGBM would be nice. I suppose I can enable GPU for LightGBM by editing your latest sample ( https://github.com/microsoft/FLAML/pull/430 ) once I get to running it?

However, my current production app are in C# so I need to first find a way to bring FLAML results to .Net (I updated the latest challenges in the dicussion: https://github.com/microsoft/FLAML/discussions/409#discussioncomment-2058431) So, for now, I am just testing out GPU support. 

To test GPU: Does **"only used by TransformersEstimator"** from docs mean only **'transformer': Huggingface transformer models.** uses it? So I need to enable 'transformer' only when using gpu_per_trial for now?

**Comment by sonichi** [comment]
> @sonichi ok, thanks. Both: now just testing. In future, probably GPU for LightGBM would be nice. I suppose I can enable GPU for LightGBM by editing your latest sample ( #430 ) once I get to running it?

Correct. If you get a chance to try it, it'll be great to let me know the result.
> 
> However, my current production app are in C# so I need to first find a way to bring FLAML results to .Net (I updated the latest challenges in the dicussion: [#409 (comment)](https://github.com/microsoft/FLAML/discussions/409#discussioncomment-2058431)) So, for now, I am just testing out GPU support.
> 
> To test GPU: Does **"only used by TransformersEstimator"** from docs mean only **'transformer': Huggingface transformer models.** uses it? So I need to enable 'transformer' only when using gpu_per_trial for now?

Yes, that's correct. You can find some examples in https://microsoft.github.io/FLAML/docs/Examples/AutoML-NLP
