### ISSUE TITLE
broken link in README.md

### ISSUE THREAD

**Issue by m13uz** [microsoft/FLAML#438]
The following link should be fixed probably?  [cost-effective hyperparameter optimization](https://microsoft.github.io/FLAML/Use-Cases/Tune-User-Defined-Function#hyperparameter-optimization-algorithm)

**Comment by sonichi** [comment]
Thanks for finding it. Would you like to create a PR to fix it? The correct url is https://microsoft.github.io/FLAML/docs/Use-Cases/Tune-User-Defined-Function#hyperparameter-optimization-algorithm.
