### ISSUE TITLE
Suggestion: log all iterations

### ISSUE THREAD

**Issue by torronen** [microsoft/FLAML#441]
Currenlty, log file include all iterations which have a new best result.

However, I would like to understand better how the parameters impact results.
For example, I might want to plot model size against accuracy, or maybe even 3D surface of chosen parameters.
Although grid search may give a better picture in general, I think it might also help understand why and how tuning progresses.

Suggestion: add all iterations and parameters to log file, or add parameter that makes save all iteration to log file.

**Comment by sonichi** [comment]
That's already supported by setting `log_type="all"`.

**Comment by torronen** [comment]
thank you
