### ISSUE TITLE
Get best model : Documentation update needed [Typo] 

### ISSUE THREAD

**Issue by GDGauravDutta** [microsoft/FLAML#443]
Existing Code:
automl.fit(X_train, y_train, task="regression")
print(automl.mdoel)
# <flaml.model.LGBMEstimator object at 0x7f9b502c4550>

Correct Code:
automl.fit(X_train, y_train, task="regression")
print(automl.model)
# <flaml.model.LGBMEstimator object at 0x7f9b502c4550>

**Comment by sonichi** [comment]
Thanks. Would you like to create a PR to fix it?
