### ISSUE TITLE
Optimization metric​  Duplicate * [Typo]

### ISSUE THREAD

**Issue by GDGauravDutta** [microsoft/FLAML#444]
Existing :
Optimization metric​

'micro_f1': minimize 1 - f1_score with average="micro".
'micro_f1': minimize 1 - f1_score with average="micro".

Should be present 
Optimization metric​

'micro_f1': minimize 1 - f1_score with average="micro".
'macro_f1': minimize 1 - f1_score with average="macro".

**Comment by sonichi** [comment]
Thanks. Would you like to create a PR to fix it?
