### ISSUE TITLE
filter fit_kwargs

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#451]
Scenario: A user has multiple estimators which accept different fit_kwargs.

Suggested change:
* inspect the signature of model.fit() (in the constructor) and filter the kwargs before:
https://github.com/microsoft/FLAML/blob/b4d312412a6b11ab7d799f670eeeedcca9348f6f/flaml/model.py#L152
* add test which includes extra fit_kwargs that is not accepted by LGBM and ensure there is no error

Effect:
* Accept fit_kwargs which contain invalid kwargs for certain estimators, without requiring change in user's code.
* The inspection may slow down the training a little bit. Better do it once in the constructor rather than doing it in fit() every time.

Potential issue:
* If an estimator's fit() takes unnamed kwargs, this filtering might fail. We need to collect some specific test cases to know whether this approach is valid.

**Comment by camer314** [comment]
That is a good suggestion. Another option is to have a keyword argument on fit which is a dictionary of estimator to kwargs to eliminate any potential for unnamed kwargs.

**Comment by sonichi** [comment]
> That is a good suggestion. Another option is to have a keyword argument on fit which is a dictionary of estimator to kwargs to eliminate any potential for unnamed kwargs.

That will avoid the ambiguity. This dict should contain only the estimator-specific kwargs. The kwargs shared by all the estimators will still be passed via **fit_kwargs.

**Comment by sonichi** [comment]
closing as #452 is an alternative solution already implemented in #511
