### ISSUE TITLE
Little Typo on the webpage

### ISSUE THREAD

**Issue by baniasbaabe** [microsoft/FLAML#456]
It should be "hyperparameters" (see image) 
![image](https://user-images.githubusercontent.com/72874670/153710713-b26fdf6a-4ae2-437c-a003-3af78f406a3f.png)

**Comment by RishiKumarRay** [comment]
@sonichi i would like to go instead if doesn't raise

**Comment by sonichi** [comment]
> @sonichi i would like to go instead if doesn't raise

Thanks. Next time :)

**Comment by RishiKumarRay** [comment]
@sonichi you have invited me to become collaborator, why? I am pretty amazed 😬

**Comment by ThunderBolt-OS** [comment]
can i contribute to this , i am new to open source

**Comment by sonichi** [comment]
> can i contribute to this , i am new to open source

Sure. Please read the [contributing guide](https://microsoft.github.io/FLAML/docs/Contribute/) to start.

**Comment by GowthamChowdary** [comment]
is this issue still open? seems like there was a PR which fixes this.
