### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'FLAML_sample_size' when building an ensemble

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#475]
When building an ensemble with the automl classification example in the notebook, I got the following error:

settings = {
    "time_budget": 200,  # total running time in seconds
    "metric": 'roc_auc',  # can be: 'r2', 'rmse', 'mae', 'mse', 'accuracy', 'roc_auc', 'roc_auc_ovr',
                           # 'roc_auc_ovo', 'log_loss', 'mape', 'f1', 'ap', 'ndcg', 'micro_f1', 'macro_f1'
    "task": 'classification',  # task type
    "log_file_name": 'airlines_experiment.log',  # flaml log file
    "seed": 7654321,    # random seed
    "model_history":True, 
    "ensemble": {"final_estimator": LRL1Classifier(),
                "passthrough": False,
            }
}

_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/home/r-yucao/.local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/data/home/r-yucao/.local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/data/home/r-yucao/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/data/home/r-yucao/.local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/data/home/r-yucao/.local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/home/r-yucao/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "/data/home/r-yucao/.local/lib/python3.7/site-packages/sklearn/ensemble/_base.py", line 39, in _fit_single_estimator
    estimator.fit(X, y)
  File "/data/home/r-yucao/.local/lib/python3.7/site-packages/flaml/model.py", line 1441, in fit
    model = self.estimator_class(train_dir=train_dir, **self.params)
TypeError: __init__() got an unexpected keyword argument 'FLAML_sample_size'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_2180/1965152210.py in <module>
----> 1 automl.fit(X_train=X_train, y_train=y_train, **settings)

~/.local/lib/python3.7/site-packages/flaml/automl.py in fit(self, X_train, y_train, dataframe, label, metric, task, n_jobs, gpu_per_trial, log_file_name, estimator_list, time_budget, max_iter, sample, ensemble, eval_method, log_type, model_history, split_ratio, n_splits, log_training_metric, mem_thres, pred_time_limit, train_time_limit, X_val, y_val, sample_weight_val, groups_val, groups, verbose, retrain_full, split_type, learner_selector, hpo_method, starting_points, seed, n_concurrent_trials, keep_search_state, early_stop, append_log, auto_augment, min_sample_size, use_ray, **fit_kwargs)
   2145             with training_log_writer(log_file_name, append_log) as save_helper:
   2146                 self._training_log = save_helper
-> 2147                 self._search()
   2148         else:
   2149             self._training_log = None

~/.local/lib/python3.7/site-packages/flaml/automl.py in _search(self)
   2704                 try:
   2705                     stacker.fit(
-> 2706                         self._X_train_all, self._y_train_all, **self._state.fit_kwargs
   2707                     )
   2708                     logger.info(f"ensemble: {stacker}")

~/.local/lib/python3.7/site-packages/sklearn/ensemble/_stacking.py in fit(self, X, y, sample_weight)
    439         self._le = LabelEncoder().fit(y)
    440         self.classes_ = self._le.classes_
--> 441         return super().fit(X, self._le.transform(y), sample_weight)
    442 
    443     @if_delegate_has_method(delegate='final_estimator_')

~/.local/lib/python3.7/site-packages/sklearn/ensemble/_stacking.py in fit(self, X, y, sample_weight)
    147         self.estimators_ = Parallel(n_jobs=self.n_jobs)(
    148             delayed(_fit_single_estimator)(clone(est), X, y, sample_weight)
--> 149             for est in all_estimators if est != 'drop'
    150         )
    151 

~/.local/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~/.local/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/data/anaconda3/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    426                 raise CancelledError()
    427             elif self._state == FINISHED:
--> 428                 return self.__get_result()
    429 
    430             self._condition.wait(timeout)

/data/anaconda3/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

TypeError: __init__() got an unexpected keyword argument 'FLAML_sample_size'

The version of flaml is the latest, 0.10.0.

Thank you.

**Comment by sonichi** [comment]
Are you sure it's the latest version? The log
`-> 2706 self._X_train_all, self._y_train_all, **self._state.fit_kwargs`
doesn't match the latest code.

**Comment by flippercy** [comment]
print(flaml.__version__)

0.9.3

Is it anything newer available?
