### ISSUE TITLE
A potential issue with sklearn when building an ensemble with large datasets

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#476]
Hi @sonichi:

I noticed recently that if the dataset was large (hard to specify how 'large' it has to be), there was always a memory-related error when building the ensemble:

**TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11), SIGSEGV(-11)}**

I did some search and it seems to be an error caused by the sklearn stacker used by flaml since people reported similar issues with sklearn.GridSearchCV (for example, https://stackoverflow.com/questions/55848101/memory-leak-using-gridsearchcv)

If I set n_jobs = 1, the issue disappeared. However, it took a lot more time to build the ensemble (not the base model).

Just want to inform you this issue. Any advice on better solutions (comparing with using just one CPU) is welcomed.

Thank you.

**Comment by sonichi** [comment]
Does it fail when `n_jobs=2`?

**Comment by flippercy** [comment]
I tried it with my internal datasets, default estimators from flaml and n_jobs=2; the issue still happened.

TerminatedWorkerError                     Traceback (most recent call last)
~/windows/Scorecards/Apps/R/Model-Development-Process/FLAML_Customized_Learners.py in <module>
      1 automl.fit(X_train = data_dev_balanced_B_X, y_train = data_dev_balanced_B_y,  sample_weight=data_dev_balanced_B_w,
      2           X_val = data_val_B_X, y_val = data_val_B_y, sample_weight_val=data_val_B_w,
----> 3           **settings)

~/.virtualenvs/r-reticulate/lib/python3.6/site-packages/flaml/automl.py in fit(self, X_train, y_train, dataframe, label, metric, task, n_jobs, log_file_name, estimator_list, time_budget, max_iter, sample, ensemble, eval_method, log_type, model_history, split_ratio, n_splits, log_training_metric, mem_thres, pred_time_limit, train_time_limit, X_val, y_val, sample_weight_val, groups_val, groups, verbose, retrain_full, split_type, learner_selector, hpo_method, starting_points, seed, n_concurrent_trials, keep_search_state, early_stop, append_log, auto_augment, min_sample_size, use_ray, **fit_kwargs)
   2270             with training_log_writer(log_file_name, append_log) as save_helper:
   2271                 self._training_log = save_helper
-> 2272                 self._search()
   2273         else:
   2274             self._training_log = None

~/.virtualenvs/r-reticulate/lib/python3.6/site-packages/flaml/automl.py in _search(self)
   2841                 try:
   2842                     stacker.fit(
-> 2843                         self._X_train_all, self._y_train_all, **self._state.fit_kwargs
   2844                     )
   2845                     logger.info(f"ensemble: {stacker}")

~/.virtualenvs/r-reticulate/lib/python3.6/site-packages/sklearn/ensemble/_stacking.py in fit(self, X, y, sample_weight)
    439         self._le = LabelEncoder().fit(y)
    440         self.classes_ = self._le.classes_
--> 441         return super().fit(X, self._le.transform(y), sample_weight)
    442 
    443     @if_delegate_has_method(delegate='final_estimator_')

~/.virtualenvs/r-reticulate/lib/python3.6/site-packages/sklearn/ensemble/_stacking.py in fit(self, X, y, sample_weight)
    147         self.estimators_ = Parallel(n_jobs=self.n_jobs)(
    148             delayed(_fit_single_estimator)(clone(est), X, y, sample_weight)
--> 149             for est in all_estimators if est != 'drop'
    150         )
    151 

~/.virtualenvs/r-reticulate/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~/.virtualenvs/r-reticulate/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~/.virtualenvs/r-reticulate/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

~/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}

**Comment by sonichi** [comment]
Does `n_jobs=2` work when the dataset is smaller? If so, then it means that your RAM is not large enough to train 2 models at the same time.

**Comment by flippercy** [comment]
It does. Actually, if the dataset is small enough, such as the one used by your notebook example, n_jobs is not an issue at all.

On the other hand, I am a bit suspicious that my RAM is not large enough for training even two models at the same time with the modeling dataset. It has 200GB+ RAM and during the training process we monitored the usage of RAM at the backend; it never exceeded 40% (80GB) before the process failed. The datasets we used are always tabular, one is approximately 180000 * 250 and the other 400000 * 50. 

Any advice on how to verify the hypothesis of RAM exhaustion? 

Thank you.

**Comment by sonichi** [comment]
> It does. Actually, if the dataset is small enough, such as the one used by your notebook example, n_jobs is not an issue at all.
> 
> On the other hand, I am a bit suspicious that my RAM is not large enough for training even two models at the same time with the modeling dataset. It has 200GB+ RAM and during the training process we monitored the usage of RAM at the backend; it never exceeded 40% (80GB) before the process failed. The datasets we used are always tabular, one is approximately 180000 * 250 and the other 400000 * 50.
> 
> Any advice on how to verify the hypothesis of RAM exhaustion?
> 
> Thank you.

I guess one way to verify is to run two Python processes to train two models at the same time. If that doesn't fail, then it indicates extra memory consumption by stacking. Then, you can try running the stacking training outside flaml, using the best models found by flaml. If that still fails, then I'd suggest creating an issue in scikit-learn.
