### ISSUE TITLE
Shape of feature_importances_ vs columns

### ISSUE THREAD

**Issue by lokijota** [microsoft/FLAML#496]
Hi,

I have trained a regression model that ended up with this lgbm config:

```jason
 {'n_estimators': 257, 'num_leaves': 25, 'min_child_samples': 2, 'learning_rate': 0.7580647590327124, 'log_max_bin': 9, 'colsample_bytree': 0.6013779332617044, 'reg_alpha': 0.0009765625, 'reg_lambda': 0.0012849550556250729}
```

When I try the code in the FAQ to plot the feature importances:

```python
import matplotlib.pyplot as plt

plt.barh(test_data.columns, automl.model.estimator.feature_importances_)
```

I get this error:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-206-f584997f5ef7> in <module>
      1 import matplotlib.pyplot as plt
      2 
----> 3 plt.barh(test_data.columns, automl.model.estimator.feature_importances_)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/pyplot.py in barh(y, width, height, left, align, **kwargs)
   2501 def barh(y, width, height=0.8, left=None, *, align='center', **kwargs):
   2502     return gca().barh(
-> 2503         y, width, height=height, left=left, align=align, **kwargs)
   2504 
   2505 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/axes/_axes.py in barh(self, y, width, height, left, align, **kwargs)
   2629         kwargs.setdefault('orientation', 'horizontal')
   2630         patches = self.bar(x=left, height=height, width=width, bottom=y,
-> 2631                            align=align, **kwargs)
   2632         return patches
   2633 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1436     def inner(ax, *args, data=None, **kwargs):
   1437         if data is None:
-> 1438             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1439 
   1440         bound = new_sig.bind(ax, *args, **kwargs)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/axes/_axes.py in bar(self, x, height, width, bottom, align, **kwargs)
   2430         x, height, width, y, linewidth = np.broadcast_arrays(
   2431             # Make args iterable too.
-> 2432             np.atleast_1d(x), height, width, y, linewidth)
   2433 
   2434         # Now that units have been converted, set the tick locations.

<__array_function__ internals> in broadcast_arrays(*args, **kwargs)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/numpy/lib/stride_tricks.py in broadcast_arrays(subok, *args)
    256     args = [np.array(_m, copy=False, subok=subok) for _m in args]
    257 
--> 258     shape = _broadcast_shape(*args)
    259 
    260     if all(array.shape == shape for array in args):

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/numpy/lib/stride_tricks.py in _broadcast_shape(*args)
    187     # use the old-iterator because np.nditer does not handle size 0 arrays
    188     # consistently
--> 189     b = np.broadcast(*args[:32])
    190     # unfortunately, it cannot handle 32 or more arguments directly
    191     for pos in range(32, len(args), 31):

ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

If I go compare the shapes, I get:

```python
automl.model.estimator.feature_importances_.shape
(26,)
```

```python
test_data.columns.shape # train data has same shape
(20,)
```

So for some reason the feature_importances_ have 6 more columns, which I am absolutely sure are **not in the training or test datasets**.

Any ideas!?

This has happened a couple of times, I don't know what those 6 extra columns are and how to handle them.

BTW, the feature importances I have are, but I don't know the columns they correspond to:

```
automl.model.estimator.feature_importances_

array([ 111, 1037,   61,  195,  371,  109,  195,  383,    1,  154,   57,
        121,   81,   34,    1,   65,   91,   15,   31,  348,  358,  644,
        480,  401,  428,  396], dtype=int32)
```

**Comment by lokijota** [comment]
Using 

```python
plt.barh(automl.model.estimator.feature_name_, automl.model.estimator.feature_importances_)
```

For some reason works.

**Comment by lokijota** [comment]
Reopening issue. The above code,

```python
plt.barh(automl.model.estimator.feature_name_, automl.model.estimator.feature_importances_)
```

Doesn't (from here: https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML) seem to work for the extra trees regressor. Is there any way to get the feature names (inc the ones that FLAML generates for datetime features), that works for all the regressors?

**Comment by qingyun-wu** [comment]
> Reopening issue. The above code,
> 
> ```python
> plt.barh(automl.model.estimator.feature_name_, automl.model.estimator.feature_importances_)
> ```
> 
> Doesn't (from here: https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML) seem to work for the extra trees regressor. Is there any way to get the feature names (inc the ones that FLAML generates for datetime features), that works for all the regressors?
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-423-dcecb4c4ca4f> in <module>
> ----> 1 featureimportancedf = pd.DataFrame(automl.model.estimator.feature_name_, columns=['feature_name'])
>       2 featureimportancedf['feature_importance'] = automl.model.estimator.feature_importances_
>       3 featureimportancedf.sort_values('feature_importance', ascending=True, inplace=True)
>       4 featureimportancedf
>       5 
> 
> AttributeError: 'ExtraTreesRegressor' object has no attribute 'feature_name_'
> ```

Hi @lokijota, according to [ExtraTreesRegressor's documentation](https://scikit-learn.org/stable/modules/generated/sklearn.tree.ExtraTreeRegressor.html#sklearn.tree.ExtraTreeRegressor), you can use `feature_names_in_` to get the feature names. Currently, flaml is not providing a unified way to get feature names, and you need to check the attribute name for feature names in the specific model used. It is possible to add this functionality, though. We will consider adding it in the future. It is even more desirable if you can add it or if you can find a volunteer contributor to add it.

**Comment by qingyun-wu** [comment]
@Yard1, does this need for a unified way to get feature names also exist in PyCaret? If so, could you please share suggestions or pointers on how PyCaret is handling it?

**Comment by Yard1** [comment]
We just get the feature names from the dataframe used in the PyCaret experiment
