### ISSUE TITLE
How to report a failed evaluation of evaluation_function to tune?

### ISSUE THREAD

**Issue by EgorKraevTransferwise** [microsoft/FLAML#504]
I am trying to optimize a custom objective function, for which some evaluations may fail with an exception. I can catch the exceptions, but what is a graceful return value for the evaluation function to return to `tune.run` if the evaluation of that particular config has failed?

I could just return a very bad value of the metric being optimized, but wondering whether there is a better way, and couldn't find it in the docs.

Thanks a lot!

**Comment by sonichi** [comment]
Does the failure mean the configuration is bad? If so, returning a bad value of the metric is right.

**Comment by EgorKraevTransferwise** [comment]
We search over ML models from the EconML repo (and their hyperparameters), and as some models there are fairly fresh, certain models can fail on certain datasets for all sorts of sometimes unforeseen reasons; the goal is to handle that gracefully and keep searching over models/configurations that work

**Comment by EgorKraevTransferwise** [comment]
So do I understand correctly that with #505 merged, the evaluation_function should return an empty dict in this case? Would it not make sense to return a metric value of NaN instead? That way, the evaluation function could return other data in the return dict, eg details of the failure.

**Comment by sonichi** [comment]
In your scenario, I still suggest returning a bad value of the metric being optimized because the failure does imply the configuration is bad for your dataset. The empty dict is meant for undeterministic evaluation error which doesn't imply the configuration is bad.

**Comment by EgorKraevTransferwise** [comment]
But for "bad" I'd have to guess ahead of time the likely range of the metric and then return a valid float value worse than anything in that range, right? There is no support for eg a NaN metric value to indicate such a usecase?

**Comment by sonichi** [comment]
> But for "bad" I'd have to guess ahead of time the likely range of the metric and then return a valid float value worse than anything in that range, right? There is no support for eg a NaN metric value to indicate such a usecase?

You can return np.inf or -np.inf depending on whether you minimize or maximize the metric.

**Comment by EgorKraevTransferwise** [comment]
Perfect, thanks! Will try that.
