### ISSUE TITLE
Error when gpu_per_trial is not an integer.

### ISSUE THREAD

**Issue by irhawks** [microsoft/FLAML#512]
environment:
- GPU: Tesla V100 16GB, CUDA 11.1
- ray                       1.11.0
- FLAML                     1.0.0
- torch                     1.11.0

A huggingface's transformer model have the following configuration:

```json
    automl_settings = {
        "resources_per_trial": {
            "cpu": 4,
            "gpu": 0.4
        },
        "local_dir": "ray_logs/",
        "time_budget": budget,                  # setting the time budget
        "task": "seq-regression",       # setting the task as seq-classification
        "hf_args": {
            "task": "seq-regression",
            "output_dir": "data/output/",   # setting the output directory
            "ckpt_per_epoch": 4,            # setting the number of checkoints per epoch
            "model_path": "hfl/chinese-legal-electra-small-discriminator",
            "per_device_eval_batch_size": 8,   # the batch size for validation (inference)
            "fp16": True,
            "max_seq_length": 512
        },
        "max_iter": 1000,
        "per_device_train_batch_size": 8,
        "gpu_per_trial": 0.4,                 # set to 0 if no GPU is available
        "log_file_name": "seqclass.log",    # set the file to save the log for HPO
        "log_type": "all",                  # the log type for trials: "all" if logging all the trials, "better" if only keeping the better trials
        "use_ray": {"local_dir": "data/ray/output"},            # set whether to use Ray
        "n_concurrent_trials": 2,
        "keep_search_state": True,          # keeping the search state
        "metric": "mae",
        "custom_hpo_args": {
            "output_dir": "data/hpo/output/"

        }
    }
```

I want to train 2 trails in parallel by setting `n_concurrent_trials=2`. However, `gpu_per_trial=0.4` raises exception by the following code in `models.py` (line 664-672):

```{python}
        if gpu_per_trial:
            tmp_cuda_visible_devices = os.environ.get("CUDA_VISIBLE_DEVICES", "")
            self._trainer.args._n_gpu = gpu_per_trial
            if gpu_per_trial == 0:
                os.environ["CUDA_VISIBLE_DEVICES"] = "" 
            if tmp_cuda_visible_devices.count(",") != gpu_per_trial - 1:
                os.environ["CUDA_VISIBLE_DEVICES"] = ",".join(
                    [str(x) for x in range(gpu_per_trial)]
                )
```

Would it be better that we do not reset  `CUDA_VISIBLE_DEVICES` to enable training two parallel transformer trails on the same GPU?

**Comment by liususan091219** [comment]
Hi @irhawks, thanks for pointing out this problem. Indeed, so far FLAML only supports integer-valued gpu_per_trial. 

I just added a ceiling function to handle the fractional case: https://github.com/microsoft/FLAML/pull/513, it should be merged soon. Let me know if it solves your problem :)

> Would it be better that we do not reset CUDA_VISIBLE_DEVICES to enable training two parallel transformer trails on the same GPU?
Good question. The reason we reset is for handling our native tuning method (FLAML.tune). After fixing this issue, however, you should be able to tune two parallel trials using one GPU only. 

Also thank you for using the NLP module, it is a new module so your question is of great value to us!
