### ISSUE TITLE
AttributeError: 'GroupKFold' object has no attribute 'groups'

### ISSUE THREAD

**Issue by LeavesWang** [microsoft/FLAML#515]
When I set "split_type" as GroupKFold, then use fit() with setting "groups", I got the issue: _AttributeError: 'GroupKFold' object has no attribute 'groups'_ and

> ml.py:460, in evaluate_model_CV(config, estimator, X_train_all, y_train_all, budget, kf, task, eval_metric, best_val_loss, log_training_metric, fit_kwargs)
>     458     kf = kf.split(X_train_split, y_train_split)
>     459 elif isinstance(kf, GroupKFold):
> **_--> 460     groups = kf.groups_**
>     461     kf = kf.split(X_train_split, y_train_split, groups)
>     462     shuffle = False

So it seems the _groups_ value needs to be assigned in the **_evaluate_model_CV()_** function. Am I right?

**Comment by sonichi** [comment]
> When I set "split_type" as GroupKFold, then use fit() with setting "groups", I got the issue: _AttributeError: 'GroupKFold' object has no attribute 'groups'_ and
> 
> > ml.py:460, in evaluate_model_CV(config, estimator, X_train_all, y_train_all, budget, kf, task, eval_metric, best_val_loss, log_training_metric, fit_kwargs)
> > 458     kf = kf.split(X_train_split, y_train_split)
> > 459 elif isinstance(kf, GroupKFold):
> > **_--> 460     groups = kf.groups_**
> > 461     kf = kf.split(X_train_split, y_train_split, groups)
> > 462     shuffle = False
> 
> So it seems the _groups_ value needs to be assigned in the **_evaluate_model_CV()_** function. Am I right?

For clarification, did you set `split_type` as the string 'group' or as a custom GroupKFold object? In the former case, the `groups` attribute should have been assigned by flaml. In the latter case, it is not.

**Comment by LeavesWang** [comment]
Thank you, [sonichi](https://github.com/sonichi)! You are right. I changed the `split_type` from  the custom GroupKFold object created by sklearn to "groups". In addition, my task is regression and setting `split_type` as "groups". Then everything is good.

**Comment by sonichi** [comment]
> Thank you, [sonichi](https://github.com/sonichi)! You are right. I changed the `split_type` from the custom GroupKFold object created by sklearn to "groups". In addition, my task is regression and setting `split_type` as "groups". Then everything is good.

Great. I'd appreciate your feedback in this survey:
https://docs.google.com/forms/d/e/1FAIpQLSd0u4BbSzr-m9hgM8rmPlYB_JJoFXeHhuoXI9YFbHDRWrDlOQ/viewform?usp=sf_link

**Comment by bbstats** [comment]
> > When I set "split_type" as GroupKFold, then use fit() with setting "groups", I got the issue: _AttributeError: 'GroupKFold' object has no attribute 'groups'_ and
> > > ml.py:460, in evaluate_model_CV(config, estimator, X_train_all, y_train_all, budget, kf, task, eval_metric, best_val_loss, log_training_metric, fit_kwargs)
> > > 458     kf = kf.split(X_train_split, y_train_split)
> > > 459 elif isinstance(kf, GroupKFold):
> > > **_--> 460     groups = kf.groups_**
> > > 461     kf = kf.split(X_train_split, y_train_split, groups)
> > > 462     shuffle = False
> > 
> > 
> > So it seems the _groups_ value needs to be assigned in the **_evaluate_model_CV()_** function. Am I right?
> 
> For clarification, did you set `split_type` as the string 'group' or as a custom GroupKFold object? In the former case, the `groups` attribute should have been assigned by flaml. In the latter case, it is not.

Is there any solution which lets you use the GroupKFold object instead?

**Comment by sonichi** [comment]
> > > When I set "split_type" as GroupKFold, then use fit() with setting "groups", I got the issue: _AttributeError: 'GroupKFold' object has no attribute 'groups'_ and
> > > > ml.py:460, in evaluate_model_CV(config, estimator, X_train_all, y_train_all, budget, kf, task, eval_metric, best_val_loss, log_training_metric, fit_kwargs)
> > > > 458     kf = kf.split(X_train_split, y_train_split)
> > > > 459 elif isinstance(kf, GroupKFold):
> > > > **_--> 460     groups = kf.groups_**
> > > > 461     kf = kf.split(X_train_split, y_train_split, groups)
> > > > 462     shuffle = False
> > > 
> > > 
> > > So it seems the _groups_ value needs to be assigned in the **_evaluate_model_CV()_** function. Am I right?
> > 
> > 
> > For clarification, did you set `split_type` as the string 'group' or as a custom GroupKFold object? In the former case, the `groups` attribute should have been assigned by flaml. In the latter case, it is not.
> 
> Is there any solution which lets you use the GroupKFold object instead?

Yes. The solution would be create a PR and move https://github.com/microsoft/FLAML/blob/cfed6578121ac5d1e7f2212b15f6fb7babfd751d/flaml/automl.py#L1231
to https://github.com/microsoft/FLAML/blob/cfed6578121ac5d1e7f2212b15f6fb7babfd751d/flaml/automl.py#L1267
with an `if` check whether the kf object is of type GroupKFold.
Would you like to create a PR?
