### ISSUE TITLE
Does FLAML support distributed models such as pytorch ddp or distributed xgb/lgbm?

### ISSUE THREAD

**Issue by luoguohao** [microsoft/FLAML#519]
As I noticed that flaml integrating Ray to support distributed hyperparamerters tuning, but what if the model need to be distributed, how it works on FLAML or it is not supported yet ?

**Comment by luoguohao** [comment]
my mistake, i just learn that ray already supported DDP and xgb.  but as we already using kubeflow training operators for pytorch and xgb，it is possible to integrate with kubeflow directly instead of ray?

**Comment by sonichi** [comment]
> my mistake, i just learn that ray already supported DDP and xgb. but as we already using kubeflow training operators for pytorch and xgb，it is possible to integrate with kubeflow directly instead of ray?

Yes. You can modify https://github.com/microsoft/FLAML/blob/46f80dfa16a1396027a2f8fea2460f5795e3ee20/test/tune_example.py#L21 
For example, you can replace https://github.com/microsoft/FLAML/blob/46f80dfa16a1396027a2f8fea2460f5795e3ee20/test/tune_example.py#L30 with your distributed training code.
