### ISSUE TITLE
Error when specifying sample_weight with xgboost 

### ISSUE THREAD

**Issue by maycuiyan** [microsoft/FLAML#53]
line 394 of flaml/model.py, The train() method does not accept weight as legitimate argument. 
Instead, the weight should be specified in line 390 when creating dtrain.

**Comment by sonichi** [comment]
Could you try version 0.2.10 and let me know if the problem is fixed? Thanks.

**Comment by maycuiyan** [comment]
@sonichi Upgrading to 0.2.10 solves the issue. Thanks! Will close this.
