### ISSUE TITLE
Hung on a long time in fit 

### ISSUE THREAD

**Issue by HuangChiEn** [microsoft/FLAML#536]
As the title described, the console is hung on after completing the fit function.
The following figure shows the console output, it's obvious that the program should continue to perform the model evaluation, but it's hang on fit function for a long time.

![image](https://user-images.githubusercontent.com/52521165/166645621-5a62e7c4-5c5a-4395-9b33-9883e6f60da0.png)

```
# code snippet just as FLAML tutorial 
automl = AutoML()
settings = {
    "time_budget": 600,  # total running time in seconds
    "ensemble": True,
    "metric": 'micro_f1',  # can be: 'r2', 'rmse', 'mae', 'mse', 'accuracy', 'roc_auc', 'roc_auc_ovr',
                        # 'roc_auc_ovo', 'log_loss', 'mape', 'f1', 'ap', 'ndcg', 'micro_f1', 'macro_f1'
    "task": 'classification',  # task type
    "log_file_name": './automl_v0.log',  # flaml log file
    "seed": 7654321,    # random seed
}

automl.fit(tra_X, tra_y, **settings) 

print('[INFO] : show searched model detail \n')
print('Best ML leaner:', automl.best_estimator)
print('Best hyperparmeter config:', automl.best_config)
print('Best accuracy on validation data: {0:.4g}'.format(1-automl.best_loss))
print('Training duration of best run: {0:.4g} s'.format(automl.best_config_train_time))

```

**Comment by sonichi** [comment]
@HuangChiEn From the console msg, it is stuck at the step of building the ensemble model (sorry for not making that explicit in the msg). You can verify it by removing `"ensemble": True` from the settings.

**Comment by HuangChiEn** [comment]
> @HuangChiEn From the console msg, it is stuck at the step of building the ensemble model (sorry for not making that explicit in the msg). You can verify it by removing `"ensemble": True` from the settings.

Thank you ~ it works!! 😊
---
Although it's fine to remove the ensemble parameters in my case, do you mind to explain why the process will huang on while enable the "ensemble flag" ? (just curious~)

**Comment by HuangChiEn** [comment]
> > @HuangChiEn From the console msg, it is stuck at the step of building the ensemble model (sorry for not making that explicit in the msg). You can verify it by removing `"ensemble": True` from the settings.
> 
> ## Thank you ~ it works!! 😊
> Although it's fine to remove the ensemble parameters in my case, do you mind to explain why the process will huang on while enable the "ensemble flag" ? (just curious~)

I saw the related issue you opened for more deatil~
🔗 https://github.com/microsoft/FLAML/issues/537
Thank you !!
