### ISSUE TITLE
Fix the indentation of fit_kwargs_by_estimator in automl.py

### ISSUE THREAD

**Issue by liususan091219** [microsoft/FLAML#552]
The indentation of fit_kwargs_by_estimator is not consistent with custom_hp:

https://github.com/microsoft/FLAML/blob/main/flaml/automl.py#L2203

which appears inconsistent in:

https://microsoft.github.io/FLAML/docs/reference/automl

**Comment by sonichi** [comment]
The problem is that the code environment before that line is not closed. Adding ``` before the line would fix it.

**Comment by harish445** [comment]
Fixed the issue and created pull request. I am new to open-source. please review it.
