### ISSUE TITLE
Remove `cat_hp_cost` from docstr

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#557]
Remove https://github.com/microsoft/FLAML/blob/515a77ac712893700766575be67500ac4f8f22cd/flaml/searcher/flow2.py#L61-L64

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue.

**Comment by sonichi** [comment]
@Mount-Blanc Thanks for your interest. There is already a PR created. Would you like to pick another issue to work on?
