### ISSUE TITLE
Option for groupKFold for regression problems

### ISSUE THREAD

**Issue by suryajayaraman** [microsoft/FLAML#56]
Hi,

I'm trying to tune lightgbm for a regression problem and need to use groupKFold for cross-validation. 
By default, automl.fit() takes repeatedkfold as split_type. I looked up at the [documentation](https://microsoft.github.io/FLAML/), but couldn't find details regarding that. Also, how to pass the groups arguments to it. 

Thanks in advance.

**Comment by sonichi** [comment]
Hi @suryajayaraman there are two ways to go about it:
1. Add support for split_type='group' in AutoML.fit(), in addition to 'stratified' and 'uniform'. Group weights can be passed and handled in a similar way as 'sample_weight'. Feel free to create a PR.
2. Use [flaml.tune.run()](https://github.com/microsoft/FLAML/tree/documentation/flaml/tune) to which you can pass a custom function `evaluate_config`. You can put the groupKFold cross-validation inside that custom function.

**Comment by dtquandt** [comment]
+1, I'm having the same issue but for classification. Trying to understand the underlying code better so that I can think about whether I feel confident adding it myself.

**Comment by sonichi** [comment]
@dtquandt @suryajayaraman Let's discuss on gitter about it.

**Comment by sonichi** [comment]
@suryajayaraman @dtquandt The PR is created. Please let us know your suggestions.
