### ISSUE TITLE
pip install flaml failing with HTTP error 403

### ISSUE THREAD

**Issue by justinxzhao** [microsoft/FLAML#568]
Perhaps this is due to the release from 40 minutes ago, in our Github tests and running locally, we're getting an error:

```
> pip install flaml               
Collecting flaml
  ERROR: HTTP error 403 while getting https://files.pythonhosted.org/packages/61/27/8fed30d5262c19d614a435a49b55d531d3e2d18b18cb9b875e979e49f95b/FLAML-1.0.4-py3-none-any.whl#sha256=236e8e8ed9642cfeca32772aca83b78458565515c28bb61544346d5f0bcfe503 (from https://pypi.org/simple/flaml/) (requires-python:>=3.6)
ERROR: Could not install requirement flaml from https://files.pythonhosted.org/packages/61/27/8fed30d5262c19d614a435a49b55d531d3e2d18b18cb9b875e979e49f95b/FLAML-1.0.4-py3-none-any.whl#sha256=236e8e8ed9642cfeca32772aca83b78458565515c28bb61544346d5f0bcfe503 because of HTTP error 403 Client Error: Forbidden for url: https://files.pythonhosted.org/packages/61/27/8fed30d5262c19d614a435a49b55d531d3e2d18b18cb9b875e979e49f95b/FLAML-1.0.4-py3-none-any.whl for URL https://files.pythonhosted.org/packages/61/27/8fed30d5262c19d614a435a49b55d531d3e2d18b18cb9b875e979e49f95b/FLAML-1.0.4-py3-none-any.whl#sha256=236e8e8ed9642cfeca32772aca83b78458565515c28bb61544346d5f0bcfe503 (from https://pypi.org/simple/flaml/) (requires-python:>=3.6)
```

Similar error with with `pip install flaml\[blendsearch\]`

**Comment by sonichi** [comment]
I just tested and I didn't see the error:
Collecting flaml
  Downloading FLAML-1.0.4-py3-none-any.whl (195 kB)
     |████████████████████████████████| 195 kB 8.0 MB/s 

Could you try again?

**Comment by justinxzhao** [comment]
The error's gone for me now too -- glad that it was intermittent!

It's odd that `pip install flaml` was not working for about an hour or two yesterday (several of our PRs were failing), probably some issue with pythonhosted's hosting.

**Comment by sonichi** [comment]
@justinxzhao If you use flaml in your project, we'd appreciate your feedback in this survey:
https://docs.google.com/forms/d/e/1FAIpQLSd0u4BbSzr-m9hgM8rmPlYB_JJoFXeHhuoXI9YFbHDRWrDlOQ/viewform?usp=sf_link

Thank you!

**Comment by justinxzhao** [comment]
Filled out the survey!
