### ISSUE TITLE
arima and sarimax init value

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#576]
In version 1.0.2 to 1.0.5, the init value of quniform HPs in arima and sarimax is int which doesn't pass the validity check. So these init values are not respected.

I propose a change in PR #575 .

Also, I suggest adding a performance test like https://github.com/microsoft/FLAML/blob/619107edf504905b069e0ca77f117f8aca32d042/test/automl/test_notebook_example.py#L73 for the forecasting task (@int-chaos ) as well as the nlp tasks (@liususan091219 ) to prevent similar issues to happen.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi I see a merged PR for this issue
Is there something left to close this issue?
