### ISSUE TITLE
AssertionError: y_train_all must be a numpy array or a pandas series.

### ISSUE THREAD

**Issue by prateekgml** [microsoft/FLAML#577]
Hi,

While fitting the model using below kine of code:

`from flaml import AutoML
automl = AutoML()
automl.fit(train_x, train_y, task="classification", estimator_list=["catboost"])`

I am facing following error-
![image](https://user-images.githubusercontent.com/97145738/172349243-1158cfbd-eeec-4a24-8145-6cf69f49f225.png)

My running environment is: Kaggle

Let me know if I can share my notebook link to any specific id since the dataset is too long to share.

**Comment by qingyun-wu** [comment]
Hi @[prateekgml](https://github.com/prateekgml),

Can you check if your data `y_train` is a NumPy array or a pandas series of labels in shape (n, )? If not, can you first convert it to the required format?

You can share your notebook link with me if you need help.

Thank you!

**Comment by prateekgml** [comment]
Thanks @qingyun-wu 
After changing to `train_y = train["target"]` assertion error issue is resolved.

But now I am facing out of memory error while fitting the model. Can you please help me how can I proceed?

[amex-train-model.txt](https://github.com/microsoft/FLAML/files/8866693/amex-train-model.txt)

Please change extension from .txt to .ipynb to see the content of the notebook.

**Comment by prateekgml** [comment]
Hi @qingyun-wu ,

No, it did not help.
Although with taking 55% of data I am able to proceed-
`train = train.sample(frac=0.55, random_state=42)`

But now facing the following error-

`CatBoostError: catboost/private/libs/target/target_converter.cpp:375: Target contains only one unique value`

The full trace is as below-

![image](https://user-images.githubusercontent.com/97145738/172870269-75f95d99-cadf-46d4-8131-5fabce089c83.png)

**Comment by qingyun-wu** [comment]
Hi @[prateekgml](https://github.com/prateekgml), I guess only one value exists on the target attribute in your subsampled dataset, which caused the error in catboost classifier. Can you revise the way to subsample the data (make sure both the positive and negative values exist in case of a binary classification task)?

Thank you!

**Comment by prateekgml** [comment]
Thanks @qingyun-wu , after revising my dataset I am able to proceed but it seems with FLAML, we cannot proceed with a large dataset. I tried to fit the model with use_ray=True attribute but it failed with OOM error. I can proceed with only 50% data.
