### ISSUE TITLE
Nested FLAML optimizations get their search spaces tangled up

### ISSUE THREAD

**Issue by EgorKraevTransferwise** [microsoft/FLAML#580]
When using FLAML to search over models, which themselves have a FLAML regressor as a component, in the same Python process, we find that the two search spaces are confused, and the component FLAML regressors get fed arguments from the outer search space (and therefore fail).

We use joblib to work around that, so each inner FLAML regressor fit runs in a separate process spawned by joblib.

A way to reproduce is to run https://github.com/transferwise/auto-causality/blob/main/notebooks/Example.ipynb after setting `n_jobs=1` in [this line](https://github.com/transferwise/auto-causality/blob/d934d34c9ee9cba43f4ae9533836abc6dcb9ebf9/auto_causality/optimiser.py#L345) so the call runs in-process.

**Comment by sonichi** [comment]
Cause:
The global variables defined in: https://github.com/microsoft/FLAML/blob/0642b6e7bbaed8aab3fb775c51af4fda3472e242/flaml/tune/tune.py#L28-L32
would be modified when calling `tune.run()` (invoked by `flaml.AutoML`) inside `tune.run()` (invoked by `auto_causality`).

Proposed solution:
Before https://github.com/microsoft/FLAML/blob/0642b6e7bbaed8aab3fb775c51af4fda3472e242/flaml/tune/tune.py#L477
make a backup of the global variables. And recover them after this line.

**Comment by EgorKraevTransferwise** [comment]
Why do you even use global variables? Why not eg use a Borg that stores these variables per FL:AML session, with the session ID being eg a uuid4 generated at each tune.run() invocation, or something like that? Or am I missing the point?

**Comment by sonichi** [comment]
> Why do you even use global variables? Why not eg use a Borg that stores these variables per FL:AML session, with the session ID being eg a uuid4 generated at each tune.run() invocation, or something like that? Or am I missing the point?

The global variables are used for `tune.report()` call in the user-defined training function. In the user-defined training function, there is no awareness of session context. `tune.report()` needs to access and update some global variables when it's called. Even if a session id is used, the session id needs to be a global variable and we still need to do this backup-recover to handle nested `tune.run` calls. So a session id won't simplify anything.
