### ISSUE TITLE
Support for recent xgboost version

### ISSUE THREAD

**Issue by ZviBaratz** [microsoft/FLAML#598]
Hi,

I am getting a repeating `FutureWarning` from `xgboost` during fitting:
```sh
.../venv/lib/python3.9/site-packages/xgboost/data.py:192: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
```
Would be great to update the requirements to support more recent versions of`xgboost`.

Thank you very much for all your great work!

**Comment by sonichi** [comment]
@ZviBaratz I can make a PR to support the latest version of xgboost, if you are willing to review the PR and test it.

**Comment by ZviBaratz** [comment]
@sonichi thank you! Will gladly review and test 🙏

**Comment by sonichi** [comment]
Thanks. Please review and test #599
