### ISSUE TITLE
Redirect the catboost_info subfolder created by CatboostEstimator

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/FLAML#62]
Feedback from sebhrusen (from the automlbenchmark)
CatboostEstimator is creating and filling a catboost_info subfolder in the running directory. We should be able to pass a 'train_dir' param to Catboost to avoid that.

For example at AutoML level, accept a tmpdir and pass it to each algo supporting an equivalent property (or pass a dedicated subfolder, for example tmpdir/catboost for Catboost and so on).

Reference:
https://github.com/openml/automlbenchmark/pull/270

**Comment by sonichi** [comment]
or find the directory of log_file_name and pass that to catboost

**Comment by bnriiitb** [comment]
@sonichi I would like to contribute to this awesome framework. As this is my first open-source contribution. Could you provide me some guidelines?

**Comment by sonichi** [comment]
@bnriiitb Thanks for considering to contribute. Please read https://github.com/microsoft/FLAML#contributing to get started. We can chat on gitter if you have questions.
