### ISSUE TITLE
code example format in the doc

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#622]
https://microsoft.github.io/FLAML/docs/Examples/Integrate%20-%20AzureML
add a space after the comma in `subscription_id='<azure-subscription-id>',resource_group=`

**Comment by 31Sanskrati** [comment]
Can I work on issue #622

**Comment by sonichi** [comment]
> Can I work on issue #622

Yes please.

**Comment by adi611** [comment]
Hi I have fixed this in #624

**Comment by sonichi** [comment]
@adi611 There was already a PR for this issue before yours. Thanks all the same. Would you like to work on a different issue?

**Comment by adi611** [comment]
> @adi611 There was already a PR for this issue before yours. Thanks all the same. Would you like to work on a different issue?

Yes definitely
