### ISSUE TITLE
Correct the code example for parallel tuning in the documentation page

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/FLAML#630]
`ray.init(n_cpus=16)` 
should be 
`ray.init(num_cpus=16)` in the documentation page 
https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#parallel-tuning

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by adi611** [comment]
Hi @qingyun-wu thanks for assigning me this issue. I looked through other places as well and didn't find any error which resembled this one.
