### ISSUE TITLE
"n_jobs" doesn't work well

### ISSUE THREAD

**Issue by zzheng93** [microsoft/FLAML#640]
Hi, I just wanted to report an issue about `n_jobs`. Note I am using version `1.0.0`. I am not quite sure if it is still an issue for the latest version.

1. The `n_jobs` parameter for `automl.predict()` appears to be non-functional.
![image](https://user-images.githubusercontent.com/23510121/179828655-781bbea9-3f7a-42ba-aebc-71df52dcd900.png)

2. The `n_jobs=-1` parameter for `automl.model.estimator.predict()` seems use only 1 core
![image](https://user-images.githubusercontent.com/23510121/179828756-30683dbd-5f72-42dd-ae25-70643abf9db8.png)

**Comment by sonichi** [comment]
I just tried the lightgbm notebook example and all the cores are used in prediction time. Could you share your notebook?

**Comment by sonichi** [comment]
> I just tried the lightgbm notebook example and all the cores are used in prediction time. Could you share your notebook?

I found the problem now. `automl.predict()` uses all the cores but `automl.model.estimator.predict(n_jobs=-1)` doesn't. Thanks!

**Comment by zzheng93** [comment]
> 

But you can see there is no difference between n_jobs for `automl.predict()`

**Comment by sonichi** [comment]
> But you can see there is no difference between n_jobs for `automl.predict()` @sonichi

Yes, that's an easy-to-fix problem:
https://github.com/microsoft/FLAML/blob/a64956a7c8f98db6a7de7e8cc5d0ce53e9c86a03/flaml/model.py#L257
should pass `**kwargs` to `predict()`

Would you like to make a PR?

**Comment by sonichi** [comment]
There are more places like this to update, e.g.,
https://github.com/microsoft/FLAML/blob/a64956a7c8f98db6a7de7e8cc5d0ce53e9c86a03/flaml/model.py#L280
https://github.com/microsoft/FLAML/blob/a64956a7c8f98db6a7de7e8cc5d0ce53e9c86a03/flaml/model.py#L1324
https://github.com/microsoft/FLAML/blob/a64956a7c8f98db6a7de7e8cc5d0ce53e9c86a03/flaml/model.py#L2134

**Comment by zzheng93** [comment]
Thanks! Sure. I just made a PR.
