### ISSUE TITLE
Disable shuffle with Custom CV

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/FLAML#658]
Hi,

It appears that shuffling of data is enabled unless the task is of type TS_FORECAST.  I have supplied a custom CV splitter which a shuffle is then applied afterwards.  It would be preferable for shuffle to be disabled when a custom CV is provided.  Thank you for your consideration.

**Comment by sonichi** [comment]
How about setting `split_type="time"`? That will disable the automatic shuffle.

**Comment by jmrichardson** [comment]
Hi @sonichi 

Yes, but how would I pass the custom CV splitter?  I am currently using:
```

        settings = {
            "time_budget": 60,  # total running time in seconds
            "metric": optimize,  # primary metrics for regression can be chosen from: ['mae','mse','r2']
            "estimator_list": ['lgbm'],  # list of ML learners; we tune lightgbm in this example
            "task": 'regression',  # task type
            "log_file_name": 'experiment.log',  # flaml log file
            "eval_method": "cv",
            "split_type": cv,
            "seed": 321,  # random seed
        }
```

If I change split_type to "time"  I don't think I can pass a custom cv?

**Comment by sonichi** [comment]
Got it. I'll suggest making a PR to modify https://github.com/microsoft/FLAML/blob/74e6026ab903b055dcffa89f93c1481263a44091/flaml/ml.py#L485
into:
`shuffle = getattr(kf, "shuffle", task not in TS_FORECAST)`

After that, you can set `cv.shuffle=False` in your code to skip shuffle.

**Comment by jmrichardson** [comment]
That's great news and appreciate the help :)

**Comment by sonichi** [comment]
> That's great news and appreciate the help :)

Would you like to make a PR?

**Comment by jmrichardson** [comment]
Yes, I can give it a go.   Hopefully get to it tomorrow.
