### ISSUE TITLE
Disable data validation

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/FLAML#660]
I would like to be able to disable pre-processing of data as I am working with a very large dataset.  The dataset is clean and does not contain missing values.   However, it appears that flaml iterates each feature (1000s) with millions of observations to replace missing data:

`X[column] = X[column].fillna(np.nan)`

In addition it does simple imputation:

```
self.transformer = ColumnTransformer(
                    [
                        (
                            "continuous",
                            SimpleImputer(missing_values=np.nan, strategy="median"),
                            X_num.columns,
                        )
                    ]
                )
                X[num_columns] = self.transformer.fit_transform(X_num)
```

This takes a considerable amount of time and would prefer to disable data preprocessing.  Thank you for your consideration.

**Comment by sonichi** [comment]
The solution would be:
1. https://github.com/microsoft/FLAML/blob/21fa6c10ec6f963edbda99e9020ad585ae60a1a5/flaml/automl.py#L1122 -> `if issparse(X_train_all) or self._skip_transform:`
2. add a keyword argument in both `AutoML.__init__()` and `AutoML.fit()` in automl.py and set `self._skip_transform` to it before https://github.com/microsoft/FLAML/blob/21fa6c10ec6f963edbda99e9020ad585ae60a1a5/flaml/automl.py#L2429 You can refer to how other keyword arguments are handled in these two places.

**Comment by jmrichardson** [comment]
Hi @sonichi 

Should I create a PR for this change?  Happy to give a shot tomorrow.

**Comment by sonichi** [comment]
> Hi @sonichi
> 
> Should I create a PR for this change? Happy to give a shot tomorrow.

Yes please. :)

**Comment by jmrichardson** [comment]
Hi, I am not an expert in PRs and not sure if the first PR should be applied first?  If I make the modifications for this and submit a new PR I will have the updates from the first PR included in the second PR.  Is this acceptable?

**Comment by sonichi** [comment]
Thanks for the question. As long as the second PR doesn't depend on the first PR, you don't need to wait for the first PR to be merged. You can create the second PR still from the main branch and it shouldn't include the updates from the first PR. When either PR is merged to main, you can update the other PR by merging from the (new) main into the PR branch. Is that clear?
