### ISSUE TITLE
Multi-thread jobs not working on Linux (works on Windows)

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/FLAML#661]
Hi, I have an interesting problem that I have observed that I am not sure how to fix.   On my local windows PC, lightgbm model with flaml works with n_jobs=-1 where multiple threads are created and reflected in the CPU utilization on all cores (100% utilization).  However, when I use the same code and same environment on my CentOS linux server it only runs 1 thread.  Here is the code sample:

```
automl = AutoML()
        settings = {
            "time_budget": time_budget,  
            "metric": optimize, 
            "estimator_list": ['lgbm'],
            "task": 'regression',  
            "log_file_name": 'experiment.log',  
            "eval_method": "cv",
            "split_type": cv,
            "seed": 123,  # random seed
            "groups": era,
            "verbose": 99,
            "custom_hp": custom_hp,
            "early_stop": True,
            "n_jobs": -1,
            "max_iter": max_iter,
            "retrain_full": False,
        }
        automl.fit(X_train=data.drop(columns=['era', 'label']), y_train=data.label, **settings)
```

Where custom_hp is:

```
custom_hp = {
    "lgbm": {
        'n_estimators': {
            "domain": tune.randint(lower=1000, upper=3000),
            "init_value": 2000,
            "low_cost_init_value": 2,
        },
        'learning_rate': {
            "domain": tune.uniform(lower=0.1, upper=1.0),
            "init_value": 0.01,
            "low_cost_init_value": .1,
        },
        'max_depth': {
            "domain": tune.randint(lower=1, upper=12),
            "init_value": 5,
            "low_cost_init_value": 2,
        },
        'num_leaves': {
            "domain": tune.randint(lower=8, upper=64),
            "init_value": 32,
            "low_cost_init_value": 2,
        },
        'colsample_bytree': {
            "domain": tune.uniform(lower=0.1, upper=1.0),
            "init_value": 0.1,
        },
        'subsample': {
            "domain": tune.uniform(lower=0.1, upper=1.0),
            "init_value": 0.5,
        },
    },
}
```

However, if I set n_jobs to a specific number of jobs such as "n_jobs: 32" in settings dict, it kicks off multiple threads on the Linux server appropriately.  Thank you for any help.

Also, I did test to see if lgbm works correctly outside of flaml with the following code and it uses all the available threads:

```
    import lightgbm as lgb
    model = lgb.LGBMRegressor()
    model.fit(features, targets.target)
```

**Comment by sonichi** [comment]
I don't know the reason. Could you provide a minimal reproducible code+data example?

**Comment by jmrichardson** [comment]
Hi @sonichi 

I've validated that this is an issue on the server and not flaml.  I still haven't figured out what the issue is but it works fine on my other servers.  Closing and will let you know if I can determine the root cause.

**Comment by sonichi** [comment]
BTW, there are some issues in `custom_hp`. For example, the "low_cost_init_value": 2 for "n_estimators" is not inside its domain `tune.randint(lower=1000, upper=3000)`. The "init_value":0.01 for "learning_rate" is not inside its domain. "low_cost_init_value" for "learning_rate" should be removed because the cost is not affected by "learning_rate".
