### ISSUE TITLE
dot_size argument not working for interaction values scatter plot

### ISSUE THREAD

**Issue by zurKreuzigungLinks** [microsoft/FLAML#674]
As the title says. The dot_size argument is simply missing where dependence_legacy is called recursively.

`dependence_legacy(
            ind1, proj_shap_values, features, feature_names=feature_names,
            interaction_index=(None if ind1 == ind2 else ind2), display_features=display_features, ax=ax, show=False,
            xmin=xmin, xmax=xmax, x_jitter=x_jitter, alpha=alpha
        )`

**Comment by sonichi** [comment]
Where is this code snippet from?
Could you provide a complete example of how to reproduce the issue?

**Comment by zurKreuzigungLinks** [comment]
Sorry for the confusion, I actually posted on the wrong git project. :disappointed: :laughing:
