### ISSUE TITLE
Catboost and RF error with groups error

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/FLAML#676]
Hi, catboost and random forest errors with the following when providing groups in settings:

```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\fml\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "d:\projects\flaml\flaml\training_log.py", line 169, in training_log_writer
    yield w
  File "d:\projects\flaml\flaml\automl.py", line 2743, in fit
    self._search()
  File "d:\projects\flaml\flaml\automl.py", line 3307, in _search
    self._search_sequential()
  File "d:\projects\flaml\flaml\automl.py", line 3125, in _search_sequential
    analysis = tune.run(
  File "d:\projects\flaml\flaml\tune\tune.py", line 507, in run
    result = evaluation_function(trial_to_run.config)
  File "d:\projects\flaml\flaml\automl.py", line 348, in _compute_with_config_base
    ) = compute_estimator(
  File "d:\projects\flaml\flaml\ml.py", line 598, in compute_estimator
    val_loss, metric_for_logging, train_time, pred_time = evaluate_model_CV(
  File "d:\projects\flaml\flaml\ml.py", line 498, in evaluate_model_CV
    val_loss_i, metric_i, train_time_i, pred_time_i = get_val_loss(
  File "d:\projects\flaml\flaml\ml.py", line 409, in get_val_loss
    estimator.fit(X_train, y_train, budget, **fit_kwargs)
  File "d:\projects\flaml\flaml\model.py", line 1641, in fit
    model.fit(
TypeError: fit() got an unexpected keyword argument 'groups'
```

This error doesn't happen with lgbm or xgboost.  Thanks for any help.

**Comment by sonichi** [comment]
random forest doesn't support groups. Need to remove it from your estimator_list.
catboost doesn't take "groups" as a fit kwarg. It takes "group_id" instead.
Some code change is required to make catboost work. We need to rename "groups" into "group_id" in `fit_kwargs` when invoking CatboostEstimator.fit() in ml.py.

**Comment by jmrichardson** [comment]
Hi @sonichi 

For a quick test, I changed my settings dict:
```
                # "groups": era,
                "group_id": era,
```
and got:

```
  File "d:\projects\flaml\flaml\model.py", line 1641, in fit
    model.fit(
TypeError: fit() got an unexpected keyword argument 'group_id'
python-BaseException
```

Confirmed also my model in model.py where the error occurred is catboost:

```
>>>model
Out[1]: <catboost.core.CatBoostRegressor at 0x14fd2a02880>
```

Also, I am using groups for the purposes of my optimization function where the group is provided in the "groups_train" parameter.  Basically, I need the group to be able to calculate Sharpe by group.  In other words, I don't need groups for the model but rather for calculating the optimization function:

```
def sharpe(X_val, y_val, estimator, labels, X_train, y_train, weight_val=None, weight_train=None,
           config=None, groups_val=None, groups_train=None):
```

**Comment by sonichi** [comment]
> Hi @sonichi
> 
> For a quick test, I changed my settings dict:
> 
> ```
>                 # "groups": era,
>                 "group_id": era,
> ```
> 
> and got:
> 
> ```
>   File "d:\projects\flaml\flaml\model.py", line 1641, in fit
>     model.fit(
> TypeError: fit() got an unexpected keyword argument 'group_id'
> python-BaseException
> ```
> 
> Confirmed also my model in model.py where the error occurred is catboost:
> 
> ```
> >>>model
> Out[1]: <catboost.core.CatBoostRegressor at 0x14fd2a02880>
> ```
> 
> Also, I am using groups for the purposes of my optimization function where the group is provided in the "groups_train" parameter. Basically, I need the group to be able to calculate Sharpe by group. In other words, I don't need groups for the model but rather for calculating the optimization function:
> 
> ```
> def sharpe(X_val, y_val, estimator, labels, X_train, y_train, weight_val=None, weight_train=None,
>            config=None, groups_val=None, groups_train=None):
> ```

You are right. For regression catboost can't take groups as input.
If you don't need groups for the model training, you can use [custom estimator](https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#estimator-and-search-space) to inherit and override the `fit()` function from a parent estimator, e.g., CatboostEstimator. In the `fit()` function, remove "groups" from kwargs and call the parent's `fit()` function. e.g.,

**Comment by jmrichardson** [comment]
Thank you for the solution, it worked perfectly!  :)
