### ISSUE TITLE
Catboost not respecting custom_hp

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/FLAML#678]
Hi,

I have configured a custom_hp for catboost:

```
custom_hp = {
    "catboost": {
        'n_estimators': {
            "domain": tune.randint(lower=1000, upper=3000),
            "init_value": 2001,
            "low_cost_init_value": 2000,
        },
        'learning_rate': {
            "domain": tune.uniform(lower=0.1, upper=1.0),
            "init_value": 0.01,
            "low_cost_init_value": .1,
        },
        'colsample_bylevel': {
            "domain": tune.uniform(lower=0.1, upper=1.0),
            "init_value": 0.1,
        },
        'depth': {
            "domain": tune.randint(lower=1, upper=12),
            "init_value": 2,
            "low_cost_init_value": 2,
        },
        'l2_leaf_reg': {
            "domain": tune.uniform(lower=0.1, upper=20),
            "init_value": 3.0,
            "low_cost_init_value": 1.0,
        },
        'bootstrap_type': {
            "domain": tune.choice(['Bayesian', 'Bernoulli', 'MVS']),
            "init_value": "Bayesian",
            "low_cost_init_value": "Bayesian",
        },
        'grow_policy': {
            "domain": tune.choice(['Lossguide', 'Depthwise']),
            "init_value": "Lossguide",
            "low_cost_init_value": "Lossguide",
        },
    },
}
```

The first iteration of the model fit the self.params for n_estimators is 2001 as defined by init_value.  However, subsequent iterations of the fit the n_estimators is a very low value such as 3.  Initially I thought it was because my low_cost_init_value was low set at 2 but as you can see I set it to the minimun for the domain as 2000.  

Here is screen shot of first iteration where self.params are consistent with custom_hp:
![image](https://user-images.githubusercontent.com/6565528/184191388-8d426f56-d11e-419b-8718-88c5c34167e3.png)

On second iteration onward, the n_estimators are very low and outside of the custom_hp domain:
![image](https://user-images.githubusercontent.com/6565528/184191729-7eb0402f-2941-4309-b502-e013b7e0693b.png)

And here is the log after first iteration:

{"record_id": 0, "iter_per_learner": 1, "logged_metric": {"sharpe": -0.00794463007228285, "correlation": -0.00015975141980052537}, "trial_time": 95.14761304855347, "wall_clock_time": 95.15061020851135, "validation_loss": 0.00794463007228285, "config": {"early_stopping_rounds": 10, "n_estimators": 1, "colsample_bylevel": 0.1, "depth": 2, "l2_leaf_reg": 2.9999999999999996, "bootstrap_type": "Bayesian", "grow_policy": "Lossguide", "learning_rate": 0.42154280932622956}, "learner": "catboost", "sample_size": 70417}

**Comment by sonichi** [comment]
I guess it's because the time_budget is small for `AutoML.fit()`. When it's small, the training will try to finish early to meet the budget requirements. If it's not the case, could you provide an example to reproduce this behavior?

**Comment by jmrichardson** [comment]
I have the time_budget set to 24 hours so don't think that is the issue.   Here is a reproducible script:

```
from sklearn.datasets import make_regression
from flaml import AutoML
from flaml import tune


if __name__ == "__main__":

    x_train, y_train = make_regression(100000, 1000)
    custom_hp = {
            "catboost": {
            'n_estimators': {
                "domain": tune.randint(lower=1000, upper=3000),
                "init_value": 2001,
                "low_cost_init_value": 2000,
            },
            'learning_rate': {
                "domain": tune.uniform(lower=0.1, upper=1.0),
                "init_value": 0.01,
                "low_cost_init_value": .1,
            },
            'colsample_bylevel': {
                "domain": tune.uniform(lower=0.1, upper=1.0),
                "init_value": 0.1,
            },
            'depth': {
                "domain": tune.randint(lower=1, upper=12),
                "init_value": 2,
                "low_cost_init_value": 2,
            },
            'l2_leaf_reg': {
                "domain": tune.uniform(lower=0.1, upper=20),
                "init_value": 3.0,
                "low_cost_init_value": 1.0,
            },
            'bootstrap_type': {
                "domain": tune.choice(['Bayesian', 'Bernoulli', 'MVS']),
                "init_value": "Bayesian",
                "low_cost_init_value": "Bayesian",
            },
            'grow_policy': {
                "domain": tune.choice(['Lossguide', 'Depthwise']),
                "init_value": "Lossguide",
                "low_cost_init_value": "Lossguide",
            },
        },
    }
    automl = AutoML()
    settings = {
        "time_budget": 86400,  # total running time in seconds
        "metric": 'r2',  # primary metrics for regression can be chosen from: ['mae','mse','r2']
        "estimator_list": ['catboost'],
        "task": 'regression',  # task type
        "log_file_name": 'experiment.log',  # flaml log file
        "eval_method": "cv",
        "split_type": "time",
        "seed": 123,
        "custom_hp": custom_hp,
        "early_stop": True,
        "n_jobs": 4,
        "retrain_full": False,
    }
    automl.fit(X_train=x_train, y_train=y_train, **settings)
```

**Comment by sonichi** [comment]
> I have the time_budget set to 24 hours so don't think that is the issue. Here is a reproducible script:
> 
> ```
> from sklearn.datasets import make_regression
> from flaml import AutoML
> from flaml import tune
> 
> 
> if __name__ == "__main__":
> 
>     x_train, y_train = make_regression(100000, 1000)
>     custom_hp = {
>             "catboost": {
>             'n_estimators': {
>                 "domain": tune.randint(lower=1000, upper=3000),
>                 "init_value": 2001,
>                 "low_cost_init_value": 2000,
>             },
>             'learning_rate': {
>                 "domain": tune.uniform(lower=0.1, upper=1.0),
>                 "init_value": 0.01,
>                 "low_cost_init_value": .1,
>             },
>             'colsample_bylevel': {
>                 "domain": tune.uniform(lower=0.1, upper=1.0),
>                 "init_value": 0.1,
>             },
>             'depth': {
>                 "domain": tune.randint(lower=1, upper=12),
>                 "init_value": 2,
>                 "low_cost_init_value": 2,
>             },
>             'l2_leaf_reg': {
>                 "domain": tune.uniform(lower=0.1, upper=20),
>                 "init_value": 3.0,
>                 "low_cost_init_value": 1.0,
>             },
>             'bootstrap_type': {
>                 "domain": tune.choice(['Bayesian', 'Bernoulli', 'MVS']),
>                 "init_value": "Bayesian",
>                 "low_cost_init_value": "Bayesian",
>             },
>             'grow_policy': {
>                 "domain": tune.choice(['Lossguide', 'Depthwise']),
>                 "init_value": "Lossguide",
>                 "low_cost_init_value": "Lossguide",
>             },
>         },
>     }
>     automl = AutoML()
>     settings = {
>         "time_budget": 86400,  # total running time in seconds
>         "metric": 'r2',  # primary metrics for regression can be chosen from: ['mae','mse','r2']
>         "estimator_list": ['catboost'],
>         "task": 'regression',  # task type
>         "log_file_name": 'experiment.log',  # flaml log file
>         "eval_method": "cv",
>         "split_type": "time",
>         "seed": 123,
>         "custom_hp": custom_hp,
>         "early_stop": True,
>         "n_jobs": 4,
>         "retrain_full": False,
>     }
>     automl.fit(X_train=x_train, y_train=y_train, **settings)
> ```

Thanks. I didn't have enough memory to run this example, so I used `make_regression(10000, 1000)` instead. With that modification, I didn't get "n_estimators=1" but I get "n_estimators=109" becuase of early stopping. Is that desirable or do you intend to disable early stopping?

**Comment by jmrichardson** [comment]
Hi,

Sorry, the original test data was smaller which is probably why the n_esitmators was smaller.  I am getting between 100 and 200 for the make_regression example as well.  I disabled "early_stop" by commenting it out as well as making it False and still the n_estimators is less than 1000 for the domain defined in custom_hp.  This doesn't happen with xgboost or lightgbm.  That is, the n_estimators with or without early_stop is always within the domain range.

**Comment by sonichi** [comment]
> Hi,
> 
> Sorry, the original test data was smaller which is probably why the n_esitmators was smaller. I am getting between 100 and 200 for the make_regression example as well. I disabled "early_stop" by commenting it out as well as making it False and still the n_estimators is less than 1000 for the domain defined in custom_hp. This doesn't happen with xgboost or lightgbm. That is, the n_estimators with or without early_stop is always within the domain range for xgboost and lightbm but not catboost.

To clarify, the behavior of catboost has nothing to do with the "early_stop" argument in `AutoML.fit()`. The latter is used to early stop the whole AutoML process. By default catboost sets [use_best_model](https://catboost.ai/en/docs/concepts/python-reference_catboostregressor_fit#use_best_model) to True which means the best number of estimators will be used after training which could be smaller than the initial n_estimators specified. You can add `use_best_model=False` in `AutoML.fit()` to disallow that behavior.

**Comment by jmrichardson** [comment]
Hi @sonichi 

Thank you for the clarification as I had it confused.  However, I just set the the parameter and it is still setting the n_estimators to the low 100s:

`automl.fit(X_train=x_train, y_train=y_train, **settings, use_best_model=False)`

**Comment by sonichi** [comment]
> Hi @sonichi
> 
> Thank you for the clarification as I had it confused. However, I just set the the parameter and it is still setting the n_estimators to the low 100s:
> 
> `automl.fit(X_train=x_train, y_train=y_train, **settings, use_best_model=False)`

I suspect that the reason is the free memory check in the callback function. I made a PR to disable it and it worked in my local test. Would you like to test it?

**Comment by jmrichardson** [comment]
Hi @sonichi 

I just merged your PR and it does prevent it from using less estimators but on each iteration the self.params are the same.  Unless I am confused on how catboost works, I would expect that flaml would adjust those params on each iteration?

**Comment by sonichi** [comment]
> Hi @sonichi
> 
> I just merged your PR and it does prevent it from using less estimators but on each iteration the self.params are the same. Unless I am confused on how catboost works, I would expect that flaml would adjust those params on each iteration?

That doesn't happen for me. Could you provide an example?

**Comment by jmrichardson** [comment]
Sorry, I mistakenly saw that the parameters were the same on each iteration because the fit was being called for multiple splits.  You are correct, it does change the parameters after all the splits have been fitted. 

The PR does work on my end too and sorry for the confusion.
