### ISSUE TITLE
Is there a way to use a custom evaluation metric?

### ISSUE THREAD

**Issue by bnriiitb** [microsoft/FLAML#69]
I would like to define & use a custom evaluation metric.

**Comment by qingyun-wu** [comment]
Hi @bnriiitb 

You can set a customized metric in FLAML through the 'metric' argument: https://github.com/microsoft/FLAML/blob/06045703bf90f58f3b89acb01b50c8fe2c65b93b/flaml/automl.py#L811

You can find an example of such a customized metric here: https://github.com/microsoft/FLAML/blob/06045703bf90f58f3b89acb01b50c8fe2c65b93b/test/test_automl.py#L92

Let us know if you need more help! Thanks!

**Comment by bnriiitb** [comment]
Thank you @qingyun-wu this is helpful.
