### ISSUE TITLE
docker build error 

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/FLAML#715]
After correcting the command line to 

_docker build https://github.com/microsoft/FLAML.git#main -t flaml-dev_

in https://microsoft.github.io/FLAML/docs/Contribute#docker

I encounter the following error:

_Step 12/17 : RUN npm install --global yarn
 ---> Running in 290e5b6652c6
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }_

I suspect this error is caused by failing to add sudo in these lines in the Dockerfile:

_# For docs
RUN npm install --global yarn
RUN pip install pydoc-markdown
_

**Comment by skzhang1** [comment]
I have made a PR. @qingyun-wu 
https://github.com/microsoft/FLAML/pull/719
