### ISSUE TITLE
Add a hyperlink to github location

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#728]
In https://microsoft.github.io/FLAML/docs/Examples/Tune-AzureML-pipeline#azure-ml-training-pipeline:
add a hyperlink for `test/pipeline_tuning_example/` to
https://github.com/microsoft/FLAML/tree/main/test/pipeline_tuning_example

**Comment by kingsonzhang** [comment]
Hello, I believe I can fix this issue. Just to clarify, does the text
> test/pipeline_tuning_example/
also need to look like inline code, or just a hyperlink is fine?

**Comment by sonichi** [comment]
> Hello, I believe I can fix this issue. Just to clarify, does the text
> 
> > test/pipeline_tuning_example/
> 
> also need to look like inline code, or just a hyperlink is fine?

Thanks. Just a hyperlink is fine.

**Comment by kingsonzhang** [comment]
Thanks! If you could assign the issue to me, I'll submit a pull request as soon as I can
