### ISSUE TITLE
Pickle Transformer

### ISSUE THREAD

**Issue by firmai** [microsoft/FLAML#730]
It seems like I can't save the transformer object.
`
AttributeError: Can't pickle local object 'preprocess_and_suggest_hyperparams.<locals>.AutoMLTransformer'`

**Comment by liususan091219** [comment]
Hi, can you share the code so we could reproduce the issue?

**Comment by firmai** [comment]
It can be reproduced with any dataset, and then pickling the transformer object (feature_transformer)

```
        hyperparams, estimator_class, X_transformed, y_transformed, feature_transformer, label_transformer = preprocess_and_suggest_hyperparams(
            "classification", X, y, "lgbm"
        )
```

**Comment by sonichi** [comment]
> It can be reproduced with any dataset, and then pickling the transformer object (feature_transformer)
> 
> ```
>         hyperparams, estimator_class, X_transformed, y_transformed, feature_transformer, label_transformer = preprocess_and_suggest_hyperparams(
>             "classification", X, y, "lgbm"
>         )
> ```

Thanks. There is an easy solution to fix this: move the definition of `AutoMLTransformer` out of the function and take `model` and `dt` as arguments in its constructor. Would you like to make a PR?

**Comment by firmai** [comment]
Hi @sonichi thanks for the explanation, I am just getting acquainted with the library, so have decided to work around this issue for now.
