### ISSUE TITLE
Missing assignment of self._kwargs in TemporalFusionTransformerEstimator prior to call

### ISSUE THREAD

**Issue by gmdiana-hershey** [microsoft/FLAML#733]
I've been experimenting with TFT, and ran into an issue running this line https://github.com/microsoft/FLAML/blob/74557472ececcd9a90b2f7a0938c73e1cdacf326/flaml/model.py#L2290. The source code seems to be missing that assignment, as opposed to the TransformersEstimator, which has it https://github.com/microsoft/FLAML/blob/74557472ececcd9a90b2f7a0938c73e1cdacf326/flaml/model.py#L619.

**Comment by int-chaos** [comment]
oh I see the issue. should be a minor fix to `gpus=kwargs.get("gpu_per_trial", [0])`. Can you submit a quick pr that changes that?
