### ISSUE TITLE
time-based split for time series classification

### ISSUE THREAD

**Issue by firmai** [microsoft/FLAML#734]
How much work would it be to get this one through, I am just interested in using the correct time series validation protocol, and currently that can't be done if your data for time dependent classification tasks.

**Comment by sonichi** [comment]
Do you mean the task is "classification" and you want to split the data by time in validation? If so, sort your data by time, and specify `split_type="time"`. Related doc: https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML/#data-split-method

**Comment by firmai** [comment]
That's great that you have that! Makes it so easy to use.
