### ISSUE TITLE
Bug with implementation of SKLearnEstimator

### ISSUE THREAD

**Issue by velezbeltran** [microsoft/FLAML#759]
I am currently using Flaml with the Sklearn regressor as described in the documentation. In particular I have 
``` python
class MyGBM(SKLearnEstimator):
    def __init__(self, task="regression", **config):
            super().__init__(task, **config)
            self.estimator_class = HistGradientBoostingRegressor

    @classmethod
    def search_space(cls, data_size, task):
        space = {
            "max_iter": {
                "domain": tune.randint(lower=100, upper=3000),
                "low_cost_init_value": 20,
            },
            "max_leaf_nodes": {
                "domain": tune.randint(lower=2, upper=2**8),
                "low_cost_init_value": 2,
            }
        }
        return space
```
However when I use this  I get
``` console
TypeError: HistGradientBoostingRegressor.__init__() got an unexpected keyword argument 'n_jobs'
```
which I think is a result of the signatures in the sklearn class not being able to handle this argument. 

I can solve this easily by creating my own class as follows

``` python
class MyHistGradientBoostingRegressor:
    def __init__(self, **kwargs):
        kwargs.pop("n_jobs", None)
        self.model = HistGradientBoostingRegressor(**kwargs)

    def fit(self, X, y, **kwargs):
        kwargs.pop("n_jobs", None)
        self.model.fit(X, y, **kwargs)
    
    def predict(self, X, **kwargs):
        return self.model.predict(X, **kwargs)
```
and then using this class instead. However it seems that either the documentation should be changed to reflect the need for the modlel to handle `kwargs` or the code should be altered. I can take a stab at fixing this if there is interest in solving the bug.

**Comment by velezbeltran** [comment]
I added some changes. I tried going with the solution that you suggested but I believe it will not work super well only because it is called in the constructor of the `BaseEstimator` and if a person is subclassing the `SKLearnEstimator` class it is possible that by the time we call `config2params` the value of `self.estimator_class` will still be `None` so no correction can be made. I went with a slightly different approach but I am not sure what you think. Looking forward to getting your feedback @sonichi .

**Comment by sonichi** [comment]
Actually there is an easier solution, which only changes one line to your original code:
```python
class MyGBM(SKLearnEstimator):
    def __init__(self, task="regression", n_jobs=1, **config):
            super().__init__(task, **config)
            self.estimator_class = HistGradientBoostingRegressor

    @classmethod
    def search_space(cls, data_size, task):
        space = {
            "max_iter": {
                "domain": tune.randint(lower=100, upper=3000),
                "low_cost_init_value": 20,
            },
            "max_leaf_nodes": {
                "domain": tune.randint(lower=2, upper=2**8),
                "low_cost_init_value": 2,
            }
        }
        return space
```

**Comment by velezbeltran** [comment]
Ha, yes you are right. Can't believe I missed that 😁. I will close the PR and then maybe add a simple line to the documentation explaining this?

**Comment by sonichi** [comment]
> Ha, yes you are right. Can't believe I missed that 😁. I will close the PR and then maybe add a simple line to the documentation explaining this?

Yes, that works!
