### ISSUE TITLE
feature engineering for datetime columns

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#76]
Create features from columns of datetime dtype in DataTransformer's fit_transform() and transform() methods. Right now a simple conversion to float type is used.

_Originally posted by @sonichi in https://github.com/microsoft/FLAML/issues/66#issuecomment-822654160_

**Comment by gianpDomiziani** [comment]
Could such a solution be okay?
for dt_column in datetime_columns:
   X[f'year_{dt_column}'] = X[dt_column].dt.year
   X[f'month_{dt_column}'] = X[dt_column].dt.month
   X[f'day_{dt_column}'] = X[dt_column].dt.day
   X[dt_column] = X[dt_column].map(datetime.toordinal)

**Comment by sonichi** [comment]
Yes that's the gist of it. I'll consider the following: Year, Month, Day, Day of week, Day of year, Quarter, Week of the year, Hour, Minute, Second.

**Comment by sonichi** [comment]
closed by #89
