### ISSUE TITLE
Remove extra | in documentation

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#775]
![image](https://user-images.githubusercontent.com/4250911/198491700-ff7ac6ad-3cde-4071-b117-5eff94a6c678.png)
https://microsoft.github.io/FLAML/docs/Use-Cases/Tune-User-Defined-Function#details-and-guidelines-on-hyperparameter-search-space

**Comment by satya-vinay** [comment]
I would like to pick this issue.
