### ISSUE TITLE
Performance test fails due to runtime variance

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#794]
One test fails occasionally due to runtime variance:
https://github.com/microsoft/FLAML/actions/runs/3384080281/jobs/5627262984
It requires rerunning the test until it passes.
It'll be nice to fix this.

**Comment by jingdong00** [comment]
I recall this happening for the last pr. It seems that the random seed is already fixed and the variance is perhaps not due to the seed setting. Should I just set a catch for the assertion error and let it retry (say, three times?) if it fails?

**Comment by sonichi** [comment]
Thanks. I made a PR to address this issue. I think there is room for further improvement in the learner selection strategy.
