### ISSUE TITLE
How does warm start (`starting_points`) work? FLAML doesn't start training from there

### ISSUE THREAD

**Issue by harshvardhaniimi** [microsoft/FLAML#795]
FLAML does not seem to respect `starting_points` hyperparameters provided to it for [warm starting](https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#warm-start). In the following example, I am fitting the first model and storing its best parameters as `warm_start_config = automl.best_config`. Later, I do the exact same run but with `starting_points = warm_start_config`. Both runs start from the same set of hyperparameters when I expect the second run to start from first run's best hyperparameters.

# Minimum Working Example

Here is an MWE which follows the example in [documentation](https://microsoft.github.io/FLAML/docs/Examples/AutoML-for-LightGBM/). For Jupyter Notebook and logs, see [GitHub Gist](https://gist.github.com/harshvardhaniimi/9e7d06ec1338e6d04ac9bce397b52117).

````
import pandas as pd
from flaml.data import load_openml_dataset
import ast
from flaml import AutoML
automl = AutoML()

X_train, X_test, y_train, y_test = load_openml_dataset(dataset_id=537, data_dir='./')

automl = AutoML()
settings = {
    "time_budget": 120,  # total running time in seconds
    "metric": 'r2',  # primary metrics for regression can be chosen from: ['mae','mse','r2']
    "estimator_list": ['lgbm'],  # list of ML learners; we tune lightgbm in this example
    "task": 'regression',  # task type
    "log_file_name": 'houses_experiment.log',  # flaml log file
    "log_type": 'all',
    "seed": 0,    # random seed
}
automl.fit(X_train=X_train, y_train=y_train, **settings)

warm_start_config = automl.best_config

# fitting again
settings = {
    "time_budget": 120,  # total running time in seconds
    "metric": 'r2',  # primary metrics for regression can be chosen from: ['mae','mse','r2']
    "estimator_list": ['lgbm'],  # list of ML learners; we tune lightgbm in this example
    "task": 'regression',  # task type
    "log_file_name": 'houses_experiment2.log',  # flaml log file (changed name from last run)
    "log_type": 'all',
    "seed": 0,    # random seed
}
automl.fit(X_train=X_train, y_train=y_train, **settings, starting_points = warm_start_config)

````

The best hyperparameter config for the first run is 

```
config: {
'n_estimators': 648, 
'num_leaves': 426, 
'min_child_samples': 128, 
'learning_rate': 0.11448393623109943, 
'log_max_bin': 7, 
'colsample_bytree': 0.7052420443533455, 
'reg_alpha': 0.03875528654230796, 
'reg_lambda': 431.843655469006
}
```

The starting point for the second run is 

```
config: {
'n_estimators': 4,
'num_leaves': 4,
'min_child_samples': 20,
'learning_rate': 0.1,
'log_max_bin': 8,
'colsample_bytree': 1.0,
'reg_alpha': 0.000977,
'reg_lambda': 61.0
}
```

In fact, the starting point for both the runs. The logs from both runs are attached.

[houses_experiment.log](https://github.com/microsoft/FLAML/files/9932841/houses_experiment.log)
[houses_experiment2.log](https://github.com/microsoft/FLAML/files/9932845/houses_experiment2.log)

**Comment by sonichi** [comment]
Could you change `warm_start_config = automl.best_config` into `warm_start_config = automl.best_config_per_estimator" and try again?

**Comment by harshvardhaniimi** [comment]
Using `warm_start_config = automl.best_config_per_estimator` works. I feel terrible missing such small detail. Feature request: if `starting_points` is not provided in the right format, could FLAML fail loudly and not silently? Even a warning saying the starting_points is wrongly provided and not used in the output would be greatly useful.
