### ISSUE TITLE
Explain how to use group fold cross validation

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#796]
Q from user: I am having trouble with getting the API to support groupfold cross validation. Is there somewhere in the documentation where this is covered?

A: Setting `split_type="group"` and `eval_method="cv"` will do it. We should update the documentation in https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#data-split-method to make it more clear.

**Comment by coffepowered** [comment]
@sonichi, is this still relevant?

**Comment by sonichi** [comment]
> @sonichi, is this still relevant?

Yes, the documentation website hasn't been updated. Would you like to work on it?

**Comment by coffepowered** [comment]
Hello @sonichi , I tried to improve the doc for the use of group-k-fold and added a sample notebook. I hope it's relevant: it's the first time I open a PR on an os project, I hope it's okay enough.
