### ISSUE TITLE
Continue/finish training after error

### ISSUE THREAD

**Issue by dcapeluto** [microsoft/FLAML#801]
automl.fit ran for 24h for hp tuning. While ensembling, at around 13h, there was an error (AssertionError - looking at ram, maybe it was OOM). So automl.model returns "None", yet saving it, saves a +15GB file, and automl.best_estimator, best_config and best_config_per_estimator all have values. If I try predict_proba, I get "No estimator is trained. Please run fit with enough budget."

What's the procedure for "continuing training" in a more capable env? training_from_log or warm start? Can I continue training the same automl var after reloading it from memory?

Thank you!

**Comment by qingyun-wu** [comment]
Hi @dcapeluto, thank you for your question. You can warm start a new AutoML instance by setting `starting_points` following the example in this doc: https://microsoft.github.io/FLAML/docs/Use-Cases/Task-Oriented-AutoML#warm-start

Let me know if you need further help!

**Comment by qingyun-wu** [comment]
> 

Hi @dcapeluto, can you please let me know if your questions and issues are resolved? I will close this issue then. 

By the way, may I ask what is your use case scenario? We'd appreciate your feedback in this survey:
https://docs.google.com/forms/d/e/1FAIpQLSd0u4BbSzr-m9hgM8rmPlYB_JJoFXeHhuoXI9YFbHDRWrDlOQ/viewform?usp=sf_link

You are also welcome to join our discord channel https://discord.gg/Cppx2vSPVP.

**Comment by dcapeluto** [comment]
> 

Hi #qingyun-wu , thanks for your incredibly prompt response. I suppose the matter is mostly resolved. It seems that both methods you suggest achieve the same. Is there a reason to choose one over the other?

If I understand correctly, I can do starting_points with negligible time budget and the training would jump into ensemble right away.

If choosing the ratrain_from_log, should one pass the exact same **automl_config as a param? If I do, and my initial time budget was 24h, would that continue training as though the 24 HP tuning already happened, or will it do more HP tuning for another 24h?

Thank you!
