### ISSUE TITLE
Does FLAML set the random seed by default?

### ISSUE THREAD

**Issue by EgorKraevTransferwise** [microsoft/FLAML#819]
It looks like it; and I think that's a bug because that makes it very painful to use it in stochastic simulations. The way I ran into it is I was generating the estimation error distribution by repeatedly sampling a synthetic dataset (so new values every time from a continuous distribution) and fitting FLAML on it, in a for loop. 

Because FLAML apparently set the random seed, all the samples beginning from the second one were identical, making the process useless.

As in many cases bootstrapping is the only way of getting estimation errors, I think this is an important issue worth fixing.

**Comment by sonichi** [comment]
What do you use for sampling? I tested `np.random.random()` before and after `AutoML.fit()`. I got different results.

**Comment by EgorKraevTransferwise** [comment]
I use numpy as well. Can you please try doing a for loop which first calls something from np.random and then AutoML.fit()? What I expect you will see is that the second result will be different from the first one, but that every next result after that will be identical to the second one.

**Comment by sonichi** [comment]
```python
import numpy as np
from flaml import AutoML

X_train = np.arange('2014-01', '2022-01', dtype='datetime64[M]')
y_train = np.random.random(size=84)
automl = AutoML()
automl.fit(X_train=X_train[:84],  # a single column of timestamp
           y_train=y_train,  # value for each timestamp
           period=12,  # time horizon to forecast, e.g., 12 months
           task='ts_forecast', time_budget=15,  # time budget in seconds
           log_file_name="ts_forecast.log",
           eval_method="holdout",
           max_iter=2,
          )

print(y_train[:5])
y_train = np.random.random(size=84)
print(y_train[:5])

automl.fit(X_train=X_train[:84],  # a single column of timestamp
           y_train=y_train,  # value for each timestamp
           period=12,  # time horizon to forecast, e.g., 12 months
           task='ts_forecast', time_budget=15,  # time budget in seconds
           log_file_name="ts_forecast.log",
           eval_method="holdout",
           max_iter=2,
          )

y_train = np.random.random(size=84)
print(y_train[:5])
```
`np.random` is called three times. Their results are all different.

**Comment by EgorKraevTransferwise** [comment]
Ah, my apologies - tracked the issue down to [causalml code](https://github.com/uber/causalml/blob/master/causalml/metrics/visualize.py) for Qini score calculation that we are using. Thanks a lot for taking a look!
