### ISSUE TITLE
Wrong function used in documentation example

### ISSUE THREAD

**Issue by ohenry-proda** [microsoft/FLAML#854]
See https://microsoft.github.io/FLAML/docs/Use-Cases/Tune-User-Defined-Function/

```
{
"learning_rate": tune.uniform(lower=0.1, upper=0.2, q=0.02),
}
```

seemingly should be

```
{
"learning_rate": tune.quniform(lower=0.1, upper=0.2, q=0.02),
}
```

**Comment by sonichi** [comment]
Good catch. The indentation should be adjusted too. Would you like to make a PR?
