### ISSUE TITLE
I want to raise the awareness that a new top-level package flaml.spark is created by this.

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/FLAML#856]
I want to raise the awareness that a new top-level package flaml.spark is created by this.
@qingyun-wu @markharley does this look OK to you?

_Originally posted by @sonichi in https://github.com/microsoft/FLAML/pull/846#discussion_r1049156076_

**Comment by qingyun-wu** [comment]
Responses from @qingyun-wu 

Adding this top-level package seems not necessary, at least for now, to me. I am OK with this if there are reasonable justifications or if anyone has a strong opinion about this. What do you think @markharley?

(https://github.com/microsoft/FLAML/pull/846#discussion_r1053744863)
A more concrete suggestion for the top-level spark module: it is perhaps better to move it to the flaml.tune folder （in this case, the functions in the [utils.py](https://github.com/microsoft/FLAML/pull/846/files/138447b3eb02eed22e65b7561ed18478a60a19c5#diff-9a80e3fdd93858985f28b172646435385c50037c928a7c84badefe3f3828aebb), e.g., customize_learner shall be revised into a more general one. )
But this potential change could be considered in a later PR.

FYI @thinkall  @sonichi @markharley

**Comment by markharley** [comment]
Added my thoughts to the PR

**Comment by thinkall** [comment]
For spark support, we're planning two steps. The first step (PR #846 ) is to support parallel training with Spark. The second step is to support AutoML for spark dataframe and pyspark.ml models. If we consider the two steps, is it OK to put the spark folder into the flaml.automl, like the nlp module?

**Comment by sonichi** [comment]
> For spark support, we're planning two steps. The first step (PR #846 ) is to support parallel training with Spark. The second step is to support AutoML for spark dataframe and pyspark.ml models. If we consider the two steps, is it OK to put the spark folder into the flaml.automl, like the nlp module?

I think we can have both `flaml.tune.spark` and `flaml.automl.spark` for different purposes. The former contains the code in the `tune` layer and the latter contains the code in the `automl` layer.

**Comment by thinkall** [comment]
> I think we can have both `flaml.tune.spark` and `flaml.automl.spark` for different purposes. The former contains the code in the `tune` layer and the latter contains the code in the `automl` layer.

OK. Then I'll move the current code to flaml.tune.spark. Thanks.
