### ISSUE TITLE
Low cpu usage when parallel tuning

### ISSUE THREAD

**Issue by shufan007** [microsoft/FLAML#866]
Hi, first of all thanks for Your kindly reply and support.
I got a low cpu uasge wen doing parallel tuning with blendsearch. My code and parameters as below:

```
from flaml import AutoML
automl = AutoML()
automl.fit(X_train, y_train, 
        task="classification",
        estimator_list=["lgbm"],
        metric='roc_auc',
        time_budget=600, 
        n_jobs=8,
        n_concurrent_trials=2,
        hpo_method='bs')
```
Here , X_train is a ndarray with size [20000000, 39] and dtype 'float64' ,  the y_train's  dtype is 'int32'.
The task is executed in a container with 16CPU, 180G memory resources

This got a very low cpu uasge, only around 200%, not the expected 1600%. So the training trails are vary slow.

Supplementary Note：

During trails running, the following warning occurred:
WARNING trial_runner.py:886 -- Trial Runner checkpointing failed: cannot serialize a bytes object larger than 4 GiB

when I cut the size of X_train to [10000000, 39], everything looks normal, the cpu uasge reached close to 1600%.

It seems to be related to the data size of X_train, for
20000000 x 39 x 8/(1024^3) \approx 5.8GiB > 4 GiB
10000000 x 39 x 8/(1024^3) \approx 2.9GiB < 4 GiB 

Please could You kindly help me, Thanks!

**Comment by sonichi** [comment]
@Yard1 This seems an issue caused by ray. Do you have an idea?

**Comment by Yard1** [comment]
Can you point me to where you are specifying how to pass the data to Tune? @sonichi

**Comment by sonichi** [comment]
> Can you point me to where you are specifying how to pass the data to Tune? @sonichi
> 
> It appears that the data is serialized in the checkpoint, which shouldn't happen unless it's passed as a part of the config, or as a part of the reported metrics. Using `with_parameters` should not cause this behavior. This may also be caused if the searcher, scheduler or trial runner have the data as an attribute, as the entire object will be pickled on checkpoint. I'd imagine the low CPU utilization is due to serialization overheads of the data being passed, which causes the trial runner loop to get bottlenecked.

Here it is: https://github.com/microsoft/FLAML/blob/b78d0b57c498ab852aec7f8d30bc782d7914ff69/flaml/automl/automl.py#L2144

**Comment by Yard1** [comment]
@shufan007 It it possible for you to provide a fully self contained reproducible example?

**Comment by shufan007** [comment]
> @shufan007 It it possible for you to provide a fully self contained reproducible example?

I put the example here: https://github.com/shufan007/flaml_example 
Thanks!

**Comment by shufan007** [comment]
@Yard1 , @sonichi 
This behavior is probably to be caused by here:
https://github.com/microsoft/FLAML/blob/90aea9c28b6100faf86f2c204e53a68e87f10c66/flaml/automl/automl.py#L3128
Data can be passed to ‘search_alg’ through ‘self._state’ as as an attribute.
I did a test, when set 'config_constraints=None', the problems mentioned above do not exist.

**Comment by Yard1** [comment]
Thanks! I'll be looking at this myself later today, this is very helpful.

**Comment by shufan007** [comment]
> @shufan007 PR to fix this issue is up ^

Ok, thank you!
