### ISSUE TITLE
`AutoML.fit` always creates a spark session even when it doesn't need to

### ISSUE THREAD

**Issue by harupy** [microsoft/FLAML#871]
Currently, `AutoML.fit` always creates a spark session even when it doesn't need to in the following line:
https://github.com/microsoft/FLAML/blob/90aea9c28b6100faf86f2c204e53a68e87f10c66/flaml/automl/automl.py#L2607

`check_spark` calls `SparkSession.builder.getOrCreate` and creates a spark session if it doesn't exist:

https://github.com/microsoft/FLAML/blob/90aea9c28b6100faf86f2c204e53a68e87f10c66/flaml/tune/spark/utils.py#L48

I think we can skip `check_spark` in the following cases:

1. When `use_ray = True`
2. When `n_concurrent_trials = 1`

### Code to reproduce:

```python
from flaml import AutoML
from sklearn.datasets import load_iris

automl = AutoML()
X, y =load_iris(as_frame=True, return_X_y=True)
automl.fit(X, y, task="classification")
```

Output:

```
check Spark installation...This line should appear only once.

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/01/05 14:41:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[flaml.automl.automl: 01-05 14:41:48] {2712} INFO - task = classification
[flaml.automl.automl: 01-05 14:41:48] {2714} INFO - Data split method: stratified
[flaml.automl.automl: 01-05 14:41:48] {2717} INFO - Evaluation method: cv
[flaml.automl.automl: 01-05 14:41:48] {2844} INFO - Minimizing error metric: log_loss
...
```

**Comment by thinkall** [comment]
Thanks @harupy for calling out it. I'll raise a PR to fix it.

**Comment by harupy** [comment]
@thinkall Thanks!
