### ISSUE TITLE
Add bibtex entries for research publications

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#892]
https://microsoft.github.io/FLAML/docs/Research

**Comment by Animaholic** [comment]
Hello, I'd like to solve this issue as my first contribution. What I need to do is to add bibtex entries for the rest of research publications in the format of the first one, is that correct? (like @inproceedings{wang2021flaml, ...)

**Comment by qingyun-wu** [comment]
This issue is resolved in a closed PR: https://github.com/microsoft/FLAML/pull/904
