### ISSUE TITLE
error when running the ChaCha example notebook (autovw.ipynb)

### ISSUE THREAD

**Issue by qetdr** [microsoft/FLAML#893]
I tried running the `autovw.ipynb` notebook but when running the code in the **AutoVW which tunes namespace interactions** section, 
```
''' import AutoVW class from flaml package '''
from flaml import AutoVW

'''create an AutoVW instance for tuning namespace interactions'''
# configure both hyperparamters to tune, e.g., 'interactions', and fixed arguments about the online learner,
# e.g., 'quiet' in the search_space argument.
autovw_ni = AutoVW(max_live_model_num=5, search_space={'interactions': AutoVW.AUTOMATIC, 'quiet': ''})

# online learning with AutoVW
loss_list_autovw_ni = online_learning_loop(max_iter_num, vw_examples, autovw_ni)
print('Final progressive validation loss of autovw:', sum(loss_list_autovw_ni)/len(loss_list_autovw_ni))
```

am getting the following error:
```
RuntimeError: Feature interactions must involve at least two namespaces.
```

The rest of the notebook seems to be working well.

**Comment by qingyun-wu** [comment]
Hi @qetdr,

Thank you for reporting this problem. What is the vowpalwabbit version installed?  Does it satisfy the following requirement?
"vowpalwabbit>=8.10.0, <9.0.0"

Can you please install`vowpalwabbit==8.10.0` and try the notebook again? Please let me know if this does not resolve the problem.

**Comment by qetdr** [comment]
Hi @qingyun-wu,

Indeed, when executed in Google Colab (not a M1-Mac) and  with `vowpalwabbit==8.10.0` installed, the notebook works as expected. 

Thanks!

**Comment by qingyun-wu** [comment]
Great! Do you know which version you were using before (the one that caused the error)? We may need to update the version requirement for vowpalwabbit accordingly. 

Thank you!

**Comment by qetdr** [comment]
The latest one - 9.6.0. Errors were produced both when running the notebook from an M1-Mac as well as Google Colab. 

On a related note, although installing `vowpalwabbit==8.10.0` worked well in Google Colab, it seems to need a bit more work on the Mac. Here's is the end-snippet of the installation error message:

```
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> vowpalwabbit
```

I hope this helps. Please let me know if you have additional questions.
