### ISSUE TITLE
Can `xgboost`, `lightgbm`, and `pandas` be made into optional dependencies?

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#898]
### Discussed in https://github.com/microsoft/FLAML/discussions/897

<div type='discussions-op-text'>

<sup>Originally posted by **topher-lo** January 26, 2023</sup>
Hi `flaml` community and maintainers! First of all, fantastic library and incredible algorithms. My team is using `flaml.tune` to run our custom hyperparameter tuning workflows. It's economical, easy-to-use, fast, and powerful: all 💯 features for production.

There is is one problem causing us headaches though: our Docker images with `flaml` installed are too big. The culprit? `xgboost` and `lightgbm`: we aren't using these models in our ML workflow. Having to install these two dependencies just to use `flaml.tune` is really slowing down our development cycles. Moreover, we are paying for those extra unused MiBs to ECR.

Please correct me if I'm mistaken, but I don't think `lightgbm` and `xgboost` are necessary for `flaml.tune`?

P.S.
Perhaps `pandas` can also be made into an optional dependency? I know many serious data teams that have pure numpy ML workflows in production: `pandas` is just unnecessary bloat. Once again, I don't think `pandas` is required for `flaml.tune`?</div>

**Comment by sonichi** [comment]
`xgboost` and `lightgbm` can be uninstalled safely for `flaml.tune`. `pandas` is also not a hard dependency of `flaml.tune`. When `pandas` is uninstalled, an ImportError will be raised at this line: https://github.com/microsoft/FLAML/blob/cdc4201188565e74507c026f86abe540ade4cb72/flaml/__init__.py#L1
So, to make flaml.tune work when pandas is uninstalled, a try...except block needs to be added to surround that line.

**Comment by topher-lo** [comment]
@sonichi what are your thoughts on:
1. Removing xgboost and lightgbm from install_requires
2. Adding two new "extras": xgb and lgb
3. Adding in the try except for pandas?

**Comment by sonichi** [comment]
> @sonichi what are your thoughts on:
> 
> 1. Removing xgboost and lightgbm from install_requires
> 2. Adding two new "extras": xgb and lgb
> 3. Adding in the try except for pandas?

(1) and (2) will be a big disruption to existing users. I'm against it but am open to discussion.
For (3), if the goal is to make `flaml.tune` work without pandas, then adding try...except for `import AutoML` would work. If the goal is to make both `flaml.tune` and `flaml.AutoML` work without pandas, then besides adding try...except for `import pandas as pd`, also need to check all the places where `pd` is used in `automl/*.py` and make sure they don't break.

**Comment by topher-lo** [comment]
What I'm doing now for production is just pip installing flaml with `--no-deps`. I'm okay with this. As for (3), I can take a look at this if it's breaking.

**Comment by levscaut** [comment]
can you assign this issue to me? @thinkall

**Comment by thinkall** [comment]
> can you assign this issue to me? @thinkall

Assigned. Thank you @levscaut for your contribution.

**Comment by topher-lo** [comment]
I had a look in `automl`. It seems `pandas` is used quite often there. IMO I think the try...except for just `import AutoML` (to use `flaml.tune` with `--no-deps` would be ideal.
