### ISSUE TITLE
add gpt-4 support

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#954]
It shares the same API as ChatGPT. Need to double check the default settings of hyperparameters. Need to update documentation.

**Comment by torronen** [comment]
Could you also consider adding example on how to add custom API's? I think this approach might be generalizable to other kind of API's, such as search API's.

**Comment by sonichi** [comment]
> Could you also consider adding example on how to add custom API's? I think this approach might be generalizable to other kind of API's, such as search API's.

Thanks. I'm closing this issue since GPT-4 support has been added. I created a new issue based on your comment and let's discuss there.
