### ISSUE TITLE
spark timeout test fails

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#959]
https://github.com/microsoft/FLAML/actions/runs/4483383911/jobs/7882609074#step:12:118
@levscaut @thinkall 

Could you check if anything is wrong? The error doesn't always occur.

**Comment by sonichi** [comment]
Another failure: https://github.com/microsoft/FLAML/actions/runs/4491787621/jobs/7900745989?pr=958

**Comment by thinkall** [comment]
> https://github.com/microsoft/FLAML/actions/runs/4483383911/jobs/7882609074#step:12:118 @levscaut @thinkall
> 
> Could you check if anything is wrong? The error doesn't always occur.

This one is caused by the assert in force_cancel scenario. We need to increase the expected time, as it depends on the hardware. Maybe increase to 5 seconds.  @levscaut

**Comment by thinkall** [comment]
> Another failure: https://github.com/microsoft/FLAML/actions/runs/4491787621/jobs/7900745989?pr=958

This one `_catboost.CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_1679502294.329023` seems to be an issue of catboost. I'll look into more details.

**Comment by thinkall** [comment]
> Another failure: https://github.com/microsoft/FLAML/actions/runs/4491787621/jobs/7900745989?pr=958

@sonichi Is this the first time you see this error? To me, it is. I see that you reran the jobs and it succeeded.

**Comment by sonichi** [comment]
> > Another failure: https://github.com/microsoft/FLAML/actions/runs/4491787621/jobs/7900745989?pr=958
> 
> @sonichi Is this the first time you see this error? To me, it is. I see that you reran the jobs and it succeeded.

I couldn't see the full error msg earlier. Now I can. The catboost error is not the first time. So feel free to ignore it for now.

**Comment by levscaut** [comment]
It's because the exceeded time limit in test_overtime is manually set to 2s and I'm not sure if I should keep it this way. Perhaps it would be better to rerun the AutoML process with force_cancel=False, then compare and assert that the time used with force_cancel=True is shorter than when force_cancel=False.

**Comment by levscaut** [comment]
> @levscaut
> 
> Run experiments two times will increase the test time, especially when not force cancel, the time could be much longer. Let's increase the assert condition value.

sure, I'll open a PR soon.
