### ISSUE TITLE
expose feature & label transformers in automl class object

### ISSUE THREAD

**Issue by skunkwerk** [microsoft/FLAML#979]
Hi, thanks for the great library.

I'm trying to save an AutoML object's feature & label pre-processors/transformers, so that they can be run offline as part of a data pipeline.

Currently, I'm using code like this:

```
hyperparams, estimator_class, X_transformed, y_transformed, feature_transformer, label_transformer = preprocess_and_suggest_hyperparams(
    "classification", X_train, y_train, "lgbm"
)
```
but is there a way to get the feature_transformer and label_transformer exposed as an automl property, so I can just use automl?

**Comment by sonichi** [comment]
Yes, they are currently stored as `automl._transformer` and `automl._label_transformer`. You can expose them as properties. Would you like to make a PR for it?
