### ISSUE TITLE
error when using chatgpt and gpt-4 in azure openai

### ISSUE THREAD

**Issue by thinkall** [microsoft/FLAML#987]
When tune hyperparameters for azure openai models, it will raise errors if the model name and deployment name are different. It caused by the API difference between azure openai and original openai. In azure openai, model name is replaced by deployment name.

**Comment by sonichi** [comment]
what's the right way to call azure openai if the model name is different from deployment name, when not using flaml?

**Comment by thinkall** [comment]
> what's the right way to call azure openai if the model name is different from deployment name, when not using flaml?

Sorry, it's not about the model name and deployment name. FLAML is using the right way to call azure openai.

I tried many times yesterday, error messages included "Resource not found" and "key error". But today, I tried the same code again, it worked! Then I tried it again, "time out" issue raised. So I think it's just unstable.
