### ISSUE TITLE
sentence misplace

### ISSUE THREAD

**Issue by sonichi** [microsoft/FLAML#998]
In https://microsoft.github.io/FLAML/docs/Use-Cases/Auto-Generation#perform-inference-with-the-tuned-config
The sentence "A template is either a format str, or a function which produces a str from several input fields." should be moved to the end of this section: https://microsoft.github.io/FLAML/docs/Use-Cases/Auto-Generation#templating

**Comment by luckyklyist** [comment]
can anyone assigned me this issue ?

**Comment by sonichi** [comment]
> can anyone assigned me this issue ?

The issue has been assigned to you 5 days ago. Do you have any question?

**Comment by luckyklyist** [comment]
I am working on it , if there any problem comes , i will be asking to with  you

**Comment by luckyklyist** [comment]
should it be below the tempting ?
